import { crit, type MissionDef } from './types';

/**
 * German missions — the flagship content set (A1–B2, every environment).
 * Each mission is a scenario brief for an AI character, not a script:
 * `criteria` define completion and feed the hint ladder; npcPrompt /
 * npcReaction give the offline engine natural lines to improvise with.
 */
const GREET = ['hallo', 'guten tag', 'guten morgen', 'guten abend', 'hi', 'servus', 'moin', 'gruss gott'];
const BYE = ['tschuss', 'auf wiedersehen', 'bis bald', 'bis dann', 'schonen tag', 'ciao'];

export const MISSIONS_DE: MissionDef[] = [
  // ───────────────────────────── CAFÉ ─────────────────────────────
  {
    slug: 'at-the-cafe',
    lang: 'de',
    env: 'cafe',
    character: 'lena-barista',
    title: 'At the Café',
    description: 'Your first real conversation: order a drink and something to eat at Café Morgenrot, then pay.',
    objective: 'Order a drink and a snack, answer the barista\'s questions and pay.',
    scenario: 'A cosy café in Berlin-Kreuzberg on a Saturday morning. The learner is at the counter. Lena, the barista, is friendly and recommends the fresh apple strudel.',
    level: 'A1',
    difficulty: 1,
    skills: ['SPEAKING', 'VOCABULARY'],
    minutes: 5,
    xp: 100,
    keyPhrases: [
      ['Ich hätte gern …', 'I would like …'],
      ['einen Kaffee', 'a coffee'],
      ['einen Cappuccino', 'a cappuccino'],
      ['mit Milch', 'with milk'],
      ['den Kuchen', 'the cake'],
      ['Was kostet das?', 'How much is it?'],
      ['Ich möchte bezahlen.', 'I would like to pay.'],
      ['die Rechnung', 'the bill'],
    ],
    grammarFocus: 'Akkusativ: einen/eine/ein after "möchten", "nehmen", "hätte gern"',
    opening: 'Guten Morgen! Willkommen im Café Morgenrot. Was darf ich Ihnen bringen?',
    criteria: [
      crit('drink', 'Order a drink', ['kaffee', 'tee', 'cappuccino', 'espresso', 'latte', 'saft', 'wasser', 'kakao', 'milchkaffee', 'cola', 'schokolade'], 'Ich hätte gern + einen/eine/ein + drink, bitte.', 'Ich hätte gern einen Cappuccino, bitte.', 'Was möchten Sie trinken?', 'Sehr gern!'),
      crit('details', 'Say what size you want and whether you want milk', ['gross', 'klein', 'mittel', 'mit milch', 'ohne milch', 'hafermilch', 'zucker', 'normal', 'schwarz'], 'Groß/Klein, bitte. Mit/Ohne Milch.', 'Groß, bitte. Mit Hafermilch.', 'Groß oder klein? Und mit Milch?', 'Alles klar, kommt sofort.'),
      crit('food', 'Order something to eat (or politely decline)', ['kuchen', 'croissant', 'brezel', 'brotchen', 'apfelstrudel', 'strudel', 'kasekuchen', 'sandwich', 'muffin', 'torte', 'nein danke', 'nichts'], 'Ich nehme + einen/eine/ein + food. / Nein danke.', 'Ich nehme einen Apfelstrudel.', 'Möchten Sie auch etwas essen? Unser Apfelstrudel ist heute ganz frisch.', 'Gute Wahl – der ist heute wirklich lecker.'),
      crit('pay', 'Ask how much it is and pay', ['bezahlen', 'zahlen', 'rechnung', 'wie viel', 'was kostet', 'kostet', 'mit karte', 'bar'], 'Was kostet das? / Ich möchte bitte bezahlen.', 'Was kostet das, bitte?', 'Möchten Sie gleich bezahlen?', 'Das macht 7,40 Euro. Mit Karte oder bar?'),
    ],
    closingLine: 'Hier ist Ihr Bon. Einen schönen Tag noch – bis bald im Café Morgenrot!',
  },
  {
    slug: 'cafe-small-talk',
    lang: 'de',
    env: 'cafe',
    character: 'lena-barista',
    title: 'Small Talk at the Counter',
    description: 'Lena has a quiet minute. Chat about where you come from and what you do.',
    objective: 'Introduce yourself, say where you come from and what you do, and ask Lena a question back.',
    scenario: 'Mid-afternoon, the café is quiet. Lena is curious about the new regular customer.',
    level: 'A1',
    difficulty: 1,
    skills: ['SPEAKING', 'LISTENING'],
    minutes: 5,
    keyPhrases: [['Ich heiße …', 'My name is …'], ['Ich komme aus …', 'I come from …'], ['Ich arbeite als …', 'I work as …'], ['Und Sie?', 'And you?'], ['Ich wohne in …', 'I live in …']],
    grammarFocus: 'sein / heißen / kommen in the present tense',
    opening: 'Sie kommen jetzt öfter, oder? Ich bin übrigens Lena. Und wie heißen Sie?',
    criteria: [
      crit('name', 'Say your name', ['ich heisse', 'mein name', 'ich bin'], 'Ich heiße … / Mein Name ist …', 'Ich heiße Sami.', 'Wie heißen Sie?', 'Freut mich!'),
      crit('origin', 'Say where you come from', ['ich komme aus', 'komme aus', 'aus '], 'Ich komme aus + country.', 'Ich komme aus Marokko.', 'Und woher kommen Sie?', 'Oh, interessant! Da war ich noch nie.'),
      crit('job', 'Say what you do', ['ich arbeite', 'ich bin student', 'ich studiere', 'ich lerne', 'beruf', 'arbeite als'], 'Ich arbeite als … / Ich studiere …', 'Ich arbeite als Krankenpfleger.', 'Und was machen Sie beruflich?', 'Toll, das klingt spannend.'),
      crit('ask-back', 'Ask Lena a question back', ['und sie', 'und du', 'woher kommen sie', 'wie lange', 'arbeiten sie', 'gefallt'], 'Und Sie? / Woher kommen Sie?', 'Und Sie? Arbeiten Sie schon lange hier?', 'Haben Sie noch eine Frage an mich?', 'Ich arbeite seit zwei Jahren hier – und ich liebe es!'),
    ],
    closingLine: 'Schön, Sie kennenzulernen! Bis morgen!',
  },
  {
    slug: 'wrong-order',
    lang: 'de',
    env: 'cafe',
    character: 'lena-barista',
    title: 'The Wrong Order',
    description: 'You ordered tea, but you got a coffee with milk. Sort it out politely.',
    objective: 'Explain the mistake politely, say what you ordered and accept the solution.',
    scenario: 'Busy lunchtime. Lena brought the wrong drink and is stressed.',
    level: 'A2',
    difficulty: 2,
    skills: ['SPEAKING', 'GRAMMAR'],
    minutes: 6,
    keyPhrases: [['Entschuldigung, …', 'Excuse me, …'], ['Ich habe … bestellt.', 'I ordered …'], ['Das ist nicht meins.', "That isn't mine."], ['Kein Problem.', 'No problem.'], ['Könnten Sie …?', 'Could you …?']],
    grammarFocus: 'Perfekt with haben (bestellt, bekommen)',
    opening: 'So, bitte schön – ein Milchkaffee! Lassen Sie es sich schmecken.',
    criteria: [
      crit('notice', 'Politely point out the problem', ['entschuldigung', 'leider', 'ich glaube', 'falsch', 'nicht meins', 'nicht richtig'], 'Entschuldigung, ich glaube, das ist falsch.', 'Entschuldigung, ich glaube, das ist nicht meins.', 'Ist alles in Ordnung?', 'Oh nein, wirklich?'),
      crit('ordered', 'Say what you actually ordered (Perfekt)', ['habe tee bestellt', 'bestellt', 'wollte tee', 'tee'], 'Ich habe … bestellt.', 'Ich habe einen Tee bestellt.', 'Was hatten Sie denn bestellt?', 'Ach, stimmt – einen Pfefferminztee! Das tut mir leid.'),
      crit('accept', 'React to the solution', ['kein problem', 'danke', 'macht nichts', 'alles gut', 'super'], 'Kein Problem, danke! / Das macht nichts.', 'Kein Problem, danke schön!', 'Ich bringe Ihnen sofort den Tee – und der Keks ist gratis. Okay?', 'Sehr nett von Ihnen!'),
    ],
    closingLine: 'Hier ist Ihr Tee. Nochmal Entschuldigung und guten Appetit!',
  },

  // ───────────────────────────── RESTAURANT ─────────────────────────────
  {
    slug: 'table-for-two',
    lang: 'de',
    env: 'restaurant',
    character: 'tom-waiter',
    title: 'A Table for Two',
    description: 'Get a table, order a main course and a drink.',
    objective: 'Ask for a table, order food and a drink, ask for the bill.',
    scenario: 'Friday evening at Restaurant Lindenhof. The learner arrives with a friend, no reservation.',
    level: 'A1',
    difficulty: 1,
    skills: ['SPEAKING', 'VOCABULARY'],
    minutes: 6,
    keyPhrases: [['Einen Tisch für zwei, bitte.', 'A table for two, please.'], ['die Speisekarte', 'the menu'], ['Ich nehme …', "I'll have …"], ['Zum Trinken …', 'To drink …'], ['Die Rechnung, bitte.', 'The bill, please.']],
    grammarFocus: 'Akkusativ with "nehmen"',
    opening: 'Guten Abend! Haben Sie reserviert?',
    criteria: [
      crit('table', 'Ask for a table', ['tisch', 'fur zwei', 'zwei personen', 'nicht reserviert', 'keine reservierung'], 'Nein, leider nicht. Einen Tisch für zwei, bitte.', 'Nein. Haben Sie einen Tisch für zwei?', 'Für wie viele Personen?', 'Da am Fenster ist noch etwas frei. Hier ist die Speisekarte.'),
      crit('main', 'Order a main course', ['schnitzel', 'salat', 'suppe', 'pasta', 'nudeln', 'fisch', 'steak', 'pizza', 'gulasch', 'vegetarisch', 'ich nehme'], 'Ich nehme + main course.', 'Ich nehme das Schnitzel mit Pommes.', 'Was möchten Sie essen?', 'Eine gute Wahl.'),
      crit('drink', 'Order a drink', ['wasser', 'wein', 'bier', 'saft', 'cola', 'apfelschorle', 'limonade', 'tee'], 'Zum Trinken nehme ich …', 'Zum Trinken nehme ich eine Apfelschorle.', 'Und zum Trinken?', 'Kommt sofort.'),
      crit('bill', 'Ask for the bill', ['rechnung', 'zahlen', 'bezahlen'], 'Die Rechnung, bitte. / Wir möchten zahlen.', 'Wir möchten bitte zahlen.', 'Darf es noch etwas sein? Ein Dessert vielleicht?', 'Zusammen oder getrennt?'),
    ],
    closingLine: 'Vielen Dank und einen schönen Abend!',
  },
  {
    slug: 'cold-soup',
    lang: 'de',
    env: 'restaurant',
    character: 'tom-waiter',
    title: 'The Soup Is Cold',
    description: 'Your soup is cold and the waiter is in a hurry. Complain politely but firmly.',
    objective: 'Complain politely, explain the problem, and negotiate a fair solution.',
    scenario: 'A crowded lunchtime. The learner\'s tomato soup arrived lukewarm after a long wait.',
    level: 'B1',
    difficulty: 3,
    skills: ['SPEAKING', 'GRAMMAR'],
    minutes: 7,
    keyPhrases: [['Ich möchte mich beschweren.', 'I would like to complain.'], ['leider kalt', 'unfortunately cold'], ['Könnten Sie …?', 'Could you …?'], ['Wäre es möglich, …?', 'Would it be possible …?'], ['Das wäre nett.', 'That would be nice.']],
    grammarFocus: 'Konjunktiv II for polite requests (könnten, wäre, würde)',
    opening: 'So, schmeckt\'s? Ich muss gleich weiter, wir sind heute total voll.',
    criteria: [
      crit('problem', 'Describe the problem politely', ['kalt', 'lauwarm', 'nicht warm', 'leider', 'problem'], 'Entschuldigung, die Suppe ist leider kalt.', 'Entschuldigung, aber die Suppe ist leider ganz kalt.', 'Ist etwas nicht in Ordnung?', 'Oh, das tut mir leid.'),
      crit('wait', 'Mention the long wait', ['lange gewartet', 'warten', 'minuten', 'lange'], 'Wir haben schon … Minuten gewartet.', 'Außerdem haben wir schon 40 Minuten gewartet.', 'Ja, die Küche ist heute etwas langsam …', 'Sie haben recht, das ist zu lange.'),
      crit('request', 'Ask for a solution with Konjunktiv II', ['konnten sie', 'ware es moglich', 'wurden sie', 'neue suppe', 'aufwarmen', 'rabatt', 'kostenlos'], 'Könnten Sie …? / Wäre es möglich, …?', 'Könnten Sie mir bitte eine neue, warme Suppe bringen?', 'Was kann ich für Sie tun?', 'Natürlich. Ich bringe sofort eine neue – und die Suppe geht aufs Haus.'),
    ],
    closingLine: 'Nochmals Entschuldigung. Ich hoffe, der Rest schmeckt Ihnen!',
  },

  // ───────────────────────────── SUPERMARKET ─────────────────────────────
  {
    slug: 'where-is-the-milk',
    lang: 'de',
    env: 'supermarket',
    character: 'mehmet-ticket',
    title: 'Where Is the Milk?',
    description: 'Find three things in a German supermarket by asking an employee.',
    objective: 'Ask where products are, understand directions and ask about a price.',
    scenario: 'A big supermarket. An employee is stocking shelves. The learner needs milk, bread and eggs.',
    level: 'A1',
    difficulty: 1,
    skills: ['LISTENING', 'SPEAKING'],
    minutes: 5,
    keyPhrases: [['Wo finde ich …?', 'Where can I find …?'], ['die Milch', 'the milk'], ['das Brot', 'the bread'], ['die Eier', 'the eggs'], ['im Regal', 'on the shelf'], ['Was kostet …?', 'How much is …?']],
    grammarFocus: 'W-questions and articles',
    opening: 'Hallo! Kann ich Ihnen helfen?',
    criteria: [
      crit('milk', 'Ask where the milk is', ['milch'], 'Wo finde ich + die/den/das …?', 'Wo finde ich die Milch?', 'Was suchen Sie denn?', 'Die Milch ist im Kühlregal, ganz hinten links.'),
      crit('bread', 'Ask about bread', ['brot', 'brotchen', 'backerei'], 'Und wo ist das Brot?', 'Und wo gibt es Brot?', 'Brauchen Sie noch etwas?', 'Brot gibt es vorne an der Bäckertheke.'),
      crit('price', 'Ask about a price', ['kostet', 'preis', 'wie viel', 'angebot'], 'Was kostet …?', 'Was kosten die Eier?', 'Sonst noch etwas?', 'Zehn Eier kosten 2,99 Euro – heute im Angebot.'),
    ],
    closingLine: 'Gern geschehen. Schönen Einkauf noch!',
  },
  {
    slug: 'returning-a-product',
    lang: 'de',
    env: 'supermarket',
    character: 'frau-klein',
    title: 'Returning a Product',
    description: 'The headphones you bought last week are broken. Get your money back.',
    objective: 'Explain what is wrong, show the receipt and ask for a refund or exchange.',
    scenario: 'Customer service desk of an electronics store. The employee wants to know what happened.',
    level: 'A2',
    difficulty: 2,
    skills: ['SPEAKING', 'GRAMMAR'],
    minutes: 6,
    keyPhrases: [['Ich möchte das zurückgeben.', 'I would like to return this.'], ['Es funktioniert nicht.', "It doesn't work."], ['der Kassenbon', 'the receipt'], ['umtauschen', 'to exchange'], ['das Geld zurück', 'the money back']],
    grammarFocus: 'Perfekt (gekauft, funktioniert) and separable verbs',
    opening: 'Guten Tag, was kann ich für Sie tun?',
    criteria: [
      crit('return', 'Say you want to return the product', ['zuruckgeben', 'zuruckbringen', 'reklamieren', 'umtauschen'], 'Ich möchte … zurückgeben.', 'Ich möchte diese Kopfhörer zurückgeben.', 'Worum geht es denn?', 'Okay. Was ist das Problem?'),
      crit('problem', 'Explain what is wrong', ['funktioniert nicht', 'kaputt', 'geht nicht', 'defekt', 'kein ton'], 'Sie funktionieren nicht. / … ist kaputt.', 'Die linke Seite funktioniert nicht.', 'Was genau funktioniert nicht?', 'Verstehe, das ist ärgerlich.'),
      crit('receipt', 'Mention the receipt / when you bought it', ['kassenbon', 'quittung', 'beleg', 'letzte woche gekauft', 'gekauft'], 'Ich habe sie letzte Woche gekauft. Hier ist der Kassenbon.', 'Ich habe sie letzte Woche gekauft – hier ist der Kassenbon.', 'Haben Sie den Kassenbon dabei?', 'Perfekt, danke.'),
      crit('solution', 'Ask for money back or an exchange', ['geld zuruck', 'umtauschen', 'neue', 'erstatten'], 'Kann ich das Geld zurückbekommen? / Kann ich sie umtauschen?', 'Kann ich bitte mein Geld zurückbekommen?', 'Möchten Sie das Geld zurück oder neue Kopfhörer?', 'Kein Problem, das machen wir sofort.'),
    ],
    closingLine: 'Alles erledigt. Einen schönen Tag noch!',
  },

  // ───────────────────────────── TRAIN STATION ─────────────────────────────
  {
    slug: 'buying-a-ticket',
    lang: 'de',
    env: 'train-station',
    character: 'mehmet-ticket',
    title: 'Buying a Train Ticket',
    description: 'Buy a ticket to Hamburg at the ticket office.',
    objective: 'Say where you want to go, when, and choose the ticket type.',
    scenario: 'Berlin main station, ticket office. The learner wants to travel to Hamburg tomorrow morning.',
    level: 'A1',
    difficulty: 1,
    skills: ['SPEAKING', 'LISTENING'],
    minutes: 5,
    keyPhrases: [['eine Fahrkarte nach …', 'a ticket to …'], ['hin und zurück', 'return'], ['einfach', 'one way'], ['morgen früh', 'tomorrow morning'], ['Von welchem Gleis?', 'From which platform?']],
    grammarFocus: 'Prepositions nach / um / von',
    opening: 'Guten Tag, der Nächste bitte! Wohin möchten Sie fahren?',
    criteria: [
      crit('destination', 'Say your destination', ['nach hamburg', 'hamburg', 'nach'], 'Eine Fahrkarte nach …, bitte.', 'Eine Fahrkarte nach Hamburg, bitte.', 'Wohin soll es gehen?', 'Hamburg, sehr gut.'),
      crit('time', 'Say when you want to travel', ['morgen', 'heute', 'fruh', 'um ', 'uhr', 'vormittag', 'abend'], 'Morgen früh, um … Uhr.', 'Morgen früh, so um acht Uhr.', 'Wann möchten Sie fahren?', 'Um 8:06 Uhr fährt ein ICE.'),
      crit('type', 'Choose one way or return', ['hin und zuruck', 'einfach', 'ruckfahrt'], 'Einfach / Hin und zurück, bitte.', 'Hin und zurück, bitte.', 'Einfach oder hin und zurück?', 'Das macht 79 Euro.'),
      crit('platform', 'Ask from which platform the train leaves', ['gleis', 'bahnsteig', 'wo fahrt'], 'Von welchem Gleis fährt der Zug?', 'Von welchem Gleis fährt der Zug?', 'Haben Sie noch eine Frage?', 'Gleis 7. Gute Reise!'),
    ],
    closingLine: 'Hier ist Ihre Fahrkarte. Gute Reise!',
  },
  {
    slug: 'the-wrong-train',
    lang: 'de',
    env: 'train-station',
    character: 'jonas-passenger',
    title: 'The Wrong Train',
    description: 'You realise you are on the wrong train. Ask another passenger for help and find the correct route.',
    objective: 'Explain your problem, ask where the train goes and find out how to get to Potsdam.',
    scenario: 'A regional train leaving Berlin. The learner wanted to go to Potsdam, but the display says Frankfurt (Oder). Jonas, a student, sits opposite.',
    level: 'A2',
    difficulty: 2,
    skills: ['SPEAKING', 'LISTENING'],
    minutes: 6,
    keyPhrases: [['im falschen Zug', 'on the wrong train'], ['Fährt dieser Zug nach …?', 'Does this train go to …?'], ['umsteigen', 'to change trains'], ['die nächste Haltestelle', 'the next stop'], ['Wie komme ich nach …?', 'How do I get to …?']],
    grammarFocus: 'Dativ after "in" (im falschen Zug) and modal verbs',
    opening: 'Alles okay? Du schaust so besorgt auf die Anzeige.',
    criteria: [
      crit('problem', 'Explain you are on the wrong train', ['falschen zug', 'falsche zug', 'falsch', 'potsdam'], 'Ich glaube, ich bin im falschen Zug.', 'Ich glaube, ich bin im falschen Zug. Ich will nach Potsdam.', 'Wohin willst du denn?', 'Oh nein – dieser Zug fährt nach Frankfurt (Oder), also genau in die andere Richtung.'),
      crit('what-now', 'Ask what you should do', ['was soll ich', 'was kann ich', 'was mache ich', 'aussteigen', 'umsteigen', 'wie komme ich'], 'Was soll ich jetzt machen? / Wie komme ich nach …?', 'Was soll ich jetzt machen?', 'Was meinst du, was wir jetzt machen?', 'Am besten steigst du in Erkner aus und nimmst die S-Bahn zurück.'),
      crit('confirm', 'Confirm where to get off / change', ['erkner', 'nachste haltestelle', 'aussteigen', 's-bahn', 'welche linie'], 'Also steige ich in … aus und nehme …?', 'Also steige ich in Erkner aus und nehme die S-Bahn?', 'Hast du alles verstanden?', 'Genau! Die S3 Richtung Westen, dann in Potsdam Hbf.'),
      crit('thanks', 'Thank Jonas', ['danke', 'vielen dank', 'nett', 'super'], 'Vielen Dank für deine Hilfe!', 'Vielen Dank, das ist sehr nett!', 'Kein Ding. Kommst du jetzt klar?', 'Gerne! Viel Spaß in Potsdam.'),
    ],
    closingLine: 'Da vorne ist Erkner – hier musst du raus. Viel Glück!',
  },
  {
    slug: 'train-cancelled',
    lang: 'de',
    env: 'train-station',
    character: 'mehmet-ticket',
    title: 'Train Cancelled',
    description: 'Your train has been cancelled and you have an important appointment. Find an alternative.',
    objective: 'Explain your situation, ask about alternatives and your passenger rights.',
    scenario: 'The 14:12 ICE to Munich has been cancelled. Long queue at the service desk.',
    level: 'B1',
    difficulty: 3,
    skills: ['SPEAKING', 'LISTENING'],
    minutes: 7,
    keyPhrases: [['ausgefallen', 'cancelled'], ['Ich habe einen wichtigen Termin.', 'I have an important appointment.'], ['eine Alternative', 'an alternative'], ['eine Entschädigung', 'compensation'], ['Gilt mein Ticket auch für …?', 'Is my ticket also valid for …?']],
    grammarFocus: 'Subordinate clauses with weil / dass / ob',
    opening: 'Ja bitte? Wenn es um den ICE nach München geht – der ist leider ausgefallen.',
    criteria: [
      crit('situation', 'Explain why it matters (weil-clause)', ['termin', 'weil', 'wichtig', 'meeting', 'vorstellungsgesprach'], '…, weil ich einen wichtigen Termin habe.', 'Das ist ein Problem, weil ich um 18 Uhr einen wichtigen Termin habe.', 'Haben Sie es eilig?', 'Verstehe, dann schauen wir sofort.'),
      crit('alternative', 'Ask for an alternative connection', ['alternative', 'andere verbindung', 'nachste zug', 'naechste', 'ein anderer zug', 'bus'], 'Gibt es eine andere Verbindung?', 'Gibt es eine andere Verbindung nach München?', 'Was kann ich für Sie tun?', 'Es gibt einen IC um 14:40 über Nürnberg, Ankunft 19:10.'),
      crit('validity', 'Ask whether your ticket is valid', ['gilt', 'ticket', 'fahrkarte', 'gultig'], 'Gilt mein Ticket auch für diesen Zug?', 'Gilt mein Ticket auch für den IC?', 'Noch Fragen zu Ihrem Ticket?', 'Ja, die Zugbindung ist aufgehoben.'),
      crit('rights', 'Ask about compensation', ['entschadigung', 'geld zuruck', 'erstattung', 'fahrgastrechte'], 'Bekomme ich eine Entschädigung?', 'Bekomme ich eine Entschädigung für die Verspätung?', 'Kann ich sonst noch helfen?', 'Ab 60 Minuten Verspätung bekommen Sie 25 % zurück – online im Fahrgastrechte-Formular.'),
    ],
    closingLine: 'Ich drücke Ihnen die Daumen für Ihren Termin!',
  },

  // ───────────────────────────── HOTEL ─────────────────────────────
  {
    slug: 'hotel-check-in',
    lang: 'de',
    env: 'hotel',
    character: 'anna-reception',
    title: 'Hotel Check-in',
    description: 'Check in to your hotel and ask about breakfast and Wi-Fi.',
    objective: 'Give your name and booking, ask about breakfast time and the Wi-Fi.',
    scenario: 'A small hotel in Munich, early evening. Anna is at the reception.',
    level: 'A1',
    difficulty: 1,
    skills: ['SPEAKING', 'LISTENING'],
    minutes: 5,
    keyPhrases: [['Ich habe ein Zimmer reserviert.', 'I have booked a room.'], ['auf den Namen …', 'under the name …'], ['das Frühstück', 'breakfast'], ['das WLAN', 'the Wi-Fi'], ['der Schlüssel', 'the key']],
    grammarFocus: 'Perfekt "Ich habe … reserviert" and W-questions',
    opening: 'Guten Abend und herzlich willkommen im Hotel Isartor! Wie kann ich Ihnen helfen?',
    criteria: [
      crit('booking', 'Say you have a booking and give your name', ['reserviert', 'reservierung', 'gebucht', 'buchung', 'auf den namen', 'mein name'], 'Ich habe ein Zimmer reserviert, auf den Namen …', 'Ich habe ein Zimmer reserviert, auf den Namen Haddad.', 'Haben Sie reserviert?', 'Ah ja, ein Einzelzimmer für drei Nächte. Zimmer 214.'),
      crit('breakfast', 'Ask about breakfast', ['fruhstuck', 'wann', 'essen'], 'Wann gibt es Frühstück?', 'Wann gibt es Frühstück?', 'Haben Sie noch Fragen?', 'Frühstück gibt es von 7 bis 10 Uhr im Erdgeschoss.'),
      crit('wifi', 'Ask about the Wi-Fi', ['wlan', 'wifi', 'internet', 'passwort'], 'Gibt es WLAN? / Wie ist das WLAN-Passwort?', 'Wie ist das Passwort für das WLAN?', 'Brauchen Sie sonst noch etwas?', 'Das Passwort steht auf der Karte: „Isartor2024".'),
    ],
    closingLine: 'Hier ist Ihr Schlüssel. Einen angenehmen Aufenthalt!',
  },
  {
    slug: 'room-problem',
    lang: 'de',
    env: 'hotel',
    character: 'anna-reception',
    title: 'Something Is Wrong With the Room',
    description: 'The heating does not work and it is noisy. Ask for help or a different room.',
    objective: 'Describe two problems and ask for a different room.',
    scenario: 'Late at night. The learner calls reception from room 214.',
    level: 'A2',
    difficulty: 2,
    skills: ['SPEAKING', 'VOCABULARY'],
    minutes: 6,
    keyPhrases: [['Die Heizung funktioniert nicht.', "The heating doesn't work."], ['Es ist sehr laut.', "It's very loud."], ['ein anderes Zimmer', 'a different room'], ['Könnten Sie jemanden schicken?', 'Could you send someone?']],
    grammarFocus: 'Modal verbs (können, möchten) and adjectives',
    opening: 'Rezeption, guten Abend, Anna am Apparat.',
    criteria: [
      crit('heating', 'Describe the heating problem', ['heizung', 'kalt', 'warm'], 'Die Heizung funktioniert nicht. Es ist kalt.', 'Die Heizung in Zimmer 214 funktioniert nicht.', 'Was ist denn los?', 'Oh, das tut mir leid.'),
      crit('noise', 'Mention the noise', ['laut', 'larm', 'musik', 'strasse'], 'Außerdem ist es sehr laut.', 'Außerdem ist es sehr laut – die Straße ist direkt vor dem Fenster.', 'Gibt es noch etwas?', 'Ja, die Zimmer zur Straße sind leider etwas laut.'),
      crit('new-room', 'Ask for a different room', ['anderes zimmer', 'neues zimmer', 'zimmer wechseln', 'umziehen'], 'Kann ich ein anderes Zimmer bekommen?', 'Kann ich bitte ein anderes Zimmer bekommen?', 'Was möchten Sie, dass ich tue?', 'Natürlich. Zimmer 305 ist ruhig, zum Hof, und die Heizung geht.'),
    ],
    closingLine: 'Ich bringe Ihnen den neuen Schlüssel sofort hoch. Gute Nacht!',
  },

  // ───────────────────────────── CITY ─────────────────────────────
  {
    slug: 'asking-for-directions',
    lang: 'de',
    env: 'city',
    character: 'frau-weber',
    title: 'Asking for Directions',
    description: 'You are lost in the old town. Ask a friendly local how to get to the museum.',
    objective: 'Ask the way, understand the directions and check how far it is.',
    scenario: 'Old town of Heidelberg. Frau Weber is walking her dog.',
    level: 'A1',
    difficulty: 1,
    skills: ['LISTENING', 'SPEAKING'],
    minutes: 5,
    keyPhrases: [['Wie komme ich zum …?', 'How do I get to the …?'], ['geradeaus', 'straight ahead'], ['links / rechts', 'left / right'], ['Ist es weit?', 'Is it far?'], ['zu Fuß', 'on foot']],
    grammarFocus: 'zum / zur (zu + Dativ) and imperative',
    opening: 'Sie sehen ein bisschen verloren aus. Kann ich helfen?',
    criteria: [
      crit('ask', 'Ask the way to the museum', ['wie komme ich', 'museum', 'wo ist', 'suche'], 'Entschuldigung, wie komme ich zum Museum?', 'Entschuldigung, wie komme ich zum Kurpfälzischen Museum?', 'Wohin möchten Sie denn?', 'Zum Museum? Gehen Sie hier geradeaus und dann die zweite Straße links.'),
      crit('repeat', 'Check you understood the directions', ['geradeaus', 'links', 'rechts', 'zweite', 'also'], 'Also: geradeaus und dann links?', 'Also geradeaus und dann die zweite Straße links?', 'Haben Sie alles verstanden?', 'Ganz genau! Dann sehen Sie es auf der rechten Seite.'),
      crit('distance', 'Ask how far it is', ['weit', 'minuten', 'zu fuss', 'wie lange'], 'Ist es weit? / Wie lange dauert es zu Fuß?', 'Ist es weit zu Fuß?', 'Möchten Sie noch etwas wissen?', 'Nein, nur fünf Minuten zu Fuß.'),
    ],
    closingLine: 'Gern geschehen! Viel Spaß im Museum.',
  },
  {
    slug: 'new-neighbour',
    lang: 'de',
    env: 'city',
    character: 'frau-weber',
    title: 'Meeting Your Neighbour',
    description: 'Introduce yourself to your neighbour in the stairwell.',
    objective: 'Greet, introduce yourself, say which flat you live in and say goodbye.',
    scenario: 'Your new apartment building. Frau Weber from the ground floor is checking her mailbox.',
    level: 'A1',
    difficulty: 1,
    skills: ['SPEAKING'],
    minutes: 4,
    keyPhrases: [['Ich bin neu hier.', "I'm new here."], ['Ich wohne im dritten Stock.', 'I live on the third floor.'], ['Freut mich!', 'Nice to meet you!'], ['Schönen Tag noch!', 'Have a nice day!']],
    grammarFocus: 'sein, wohnen, ordinal numbers',
    opening: 'Oh, guten Tag! Sie habe ich hier ja noch nie gesehen.',
    criteria: [
      crit('greet', 'Greet and say you are new', [...GREET, 'neu hier', 'eingezogen'], 'Guten Tag! Ich bin neu hier.', 'Guten Tag! Ich bin neu hier, ich heiße Amira.', 'Wohnen Sie jetzt hier?', 'Ach, wie schön! Willkommen im Haus.'),
      crit('floor', 'Say where you live in the building', ['stock', 'etage', 'wohne', 'oben', 'dachgeschoss'], 'Ich wohne im … Stock.', 'Ich wohne im dritten Stock.', 'In welcher Wohnung wohnen Sie denn?', 'Ach, in der Wohnung von Familie Krüger! Die ist schön hell.'),
      crit('bye', 'Say goodbye politely', BYE, 'Schönen Tag noch! / Auf Wiedersehen!', 'Freut mich! Schönen Tag noch!', 'Ich muss jetzt leider weiter …', 'Ihnen auch!'),
    ],
    closingLine: 'Wenn Sie etwas brauchen – ich wohne unten links. Auf Wiedersehen!',
  },

  // ───────────────────────────── HOME ─────────────────────────────
  {
    slug: 'introduce-yourself',
    lang: 'de',
    env: 'home',
    character: 'mia-friend',
    title: 'Introduce Yourself',
    description: 'Your first day at the language course. Introduce yourself to Mia.',
    objective: 'Say your name, age, where you are from and one hobby.',
    scenario: 'First day of a language course. Mia sits next to the learner during the break.',
    level: 'A1',
    difficulty: 1,
    skills: ['SPEAKING'],
    minutes: 4,
    keyPhrases: [['Ich heiße …', 'My name is …'], ['Ich bin … Jahre alt.', "I'm … years old."], ['Mein Hobby ist …', 'My hobby is …'], ['Ich spiele gern …', 'I like playing …']],
    grammarFocus: 'sein / haben / gern + verb',
    opening: 'Hi! Ich bin Mia. Bist du auch neu im Kurs?',
    criteria: [
      crit('name', 'Say your name', ['ich heisse', 'ich bin', 'mein name'], 'Ich heiße … / Ich bin …', 'Ja! Ich heiße Karim.', 'Wie heißt du?', 'Cool, freut mich!'),
      crit('age', 'Say how old you are', ['jahre alt', 'jahre'], 'Ich bin … Jahre alt.', 'Ich bin 27 Jahre alt.', 'Und wie alt bist du, wenn ich fragen darf?', 'Ah, ich bin 25.'),
      crit('hobby', 'Talk about a hobby', ['hobby', 'gern', 'spiele', 'lese', 'koche', 'fussball', 'musik', 'tanze', 'sport'], 'Mein Hobby ist … / Ich … gern.', 'Ich spiele gern Fußball.', 'Was machst du gern in deiner Freizeit?', 'Echt? Ich auch! Wir sollten mal zusammen spielen.'),
    ],
    closingLine: 'Oh, die Pause ist vorbei. Bis gleich!',
  },
  {
    slug: 'calling-the-landlord',
    lang: 'de',
    env: 'home',
    character: 'herr-schulz',
    title: 'Calling the Landlord',
    description: 'Water is dripping from your ceiling. Call your landlord and arrange a repair.',
    objective: 'Explain the damage on the phone, insist on urgency and agree on a time.',
    scenario: 'Saturday morning. Water drips from the bathroom ceiling. The landlord, Herr Schulz, answers the phone.',
    level: 'B1',
    difficulty: 3,
    skills: ['SPEAKING', 'LISTENING'],
    minutes: 7,
    keyPhrases: [['Es tropft von der Decke.', 'Water is dripping from the ceiling.'], ['ein Wasserschaden', 'water damage'], ['so schnell wie möglich', 'as soon as possible'], ['einen Handwerker schicken', 'to send a tradesperson'], ['Passt Ihnen …?', 'Does … suit you?']],
    grammarFocus: 'Formal telephone language, temporal prepositions',
    opening: 'Schulz.',
    criteria: [
      crit('identify', 'Introduce yourself on the phone', ['hier ist', 'mein name', 'ich bin', 'wohnung', 'mieter'], 'Guten Tag, hier ist … aus der Wohnung …', 'Guten Tag Herr Schulz, hier ist Haddad aus der Wohnung im zweiten Stock.', 'Wer ist da, bitte?', 'Ah, guten Morgen. Was gibt es?'),
      crit('damage', 'Describe the water damage', ['tropft', 'wasser', 'decke', 'nass', 'wasserschaden', 'badezimmer'], 'Im Bad tropft Wasser von der Decke.', 'Im Badezimmer tropft Wasser von der Decke.', 'Was ist passiert?', 'Oh je. Das kommt bestimmt von oben.'),
      crit('urgency', 'Insist that it is urgent', ['dringend', 'sofort', 'so schnell wie moglich', 'heute', 'nicht warten'], 'Das ist dringend. Können Sie heute jemanden schicken?', 'Das ist dringend – könnten Sie bitte heute noch jemanden schicken?', 'Kann das bis Montag warten?', 'Sie haben recht, das sollte nicht warten.'),
      crit('time', 'Agree on a time', ['uhr', 'heute', 'nachmittag', 'passt', 'bin zu hause'], 'Ich bin ab … Uhr zu Hause. Passt das?', 'Ich bin ab 14 Uhr zu Hause. Passt das?', 'Wann sind Sie zu Hause?', 'Gut, der Handwerker kommt um 15 Uhr.'),
    ],
    closingLine: 'Ich rufe gleich den Handwerker an. Danke für den Anruf!',
  },

  // ───────────────────────────── HOSPITAL ─────────────────────────────
  {
    slug: 'at-the-pharmacy',
    lang: 'de',
    env: 'hospital',
    character: 'kai-pharmacist',
    title: 'At the Pharmacy',
    description: 'You have a headache and a sore throat. Get the right medicine.',
    objective: 'Describe symptoms, ask for medicine and ask how to take it.',
    scenario: 'A neighbourhood pharmacy. Kai, the pharmacist, asks a few questions.',
    level: 'A1',
    difficulty: 1,
    skills: ['SPEAKING', 'VOCABULARY'],
    minutes: 5,
    keyPhrases: [['Ich habe Kopfschmerzen.', 'I have a headache.'], ['Halsschmerzen', 'sore throat'], ['Haben Sie etwas gegen …?', 'Do you have something for …?'], ['Wie oft?', 'How often?'], ['die Tablette', 'the tablet']],
    grammarFocus: 'haben + body vocabulary',
    opening: 'Guten Tag! Was kann ich für Sie tun?',
    criteria: [
      crit('symptoms', 'Describe your symptoms', ['kopfschmerzen', 'halsschmerzen', 'fieber', 'husten', 'schnupfen', 'tut weh', 'krank'], 'Ich habe Kopfschmerzen und Halsschmerzen.', 'Ich habe Kopfschmerzen und Halsschmerzen.', 'Was fehlt Ihnen denn?', 'Oh, das klingt nach einer Erkältung.'),
      crit('medicine', 'Ask for medicine', ['etwas gegen', 'tabletten', 'medikament', 'mittel'], 'Haben Sie etwas gegen …?', 'Haben Sie etwas gegen Halsschmerzen?', 'Was brauchen Sie?', 'Ja, diese Lutschtabletten und Ibuprofen für den Kopf.'),
      crit('dose', 'Ask how often to take it', ['wie oft', 'wie viele', 'am tag', 'einnehmen'], 'Wie oft soll ich sie nehmen?', 'Wie oft soll ich die Tabletten nehmen?', 'Haben Sie noch Fragen?', 'Dreimal am Tag nach dem Essen.'),
    ],
    closingLine: 'Gute Besserung!',
  },
  {
    slug: 'at-the-doctor',
    lang: 'de',
    env: 'hospital',
    character: 'dr-hoffmann',
    title: 'At the Doctor',
    description: 'Explain how you feel to the doctor and understand her advice.',
    objective: 'Describe your symptoms, say since when, answer questions and ask for a sick note.',
    scenario: 'A family doctor\'s practice. The learner has had a fever for two days and needs a sick note for work.',
    level: 'A2',
    difficulty: 2,
    skills: ['SPEAKING', 'LISTENING'],
    minutes: 6,
    keyPhrases: [['seit zwei Tagen', 'for two days'], ['Fieber', 'fever'], ['Mir ist schlecht.', 'I feel sick.'], ['die Krankmeldung', 'the sick note'], ['Ich nehme keine Medikamente.', "I don't take any medication."]],
    grammarFocus: 'seit + Dativ, Perfekt',
    opening: 'Guten Tag, nehmen Sie bitte Platz. Was führt Sie zu mir?',
    criteria: [
      crit('symptoms', 'Describe your symptoms', ['fieber', 'kopfschmerzen', 'husten', 'schlecht', 'mude', 'bauchschmerzen'], 'Ich habe Fieber und …', 'Ich habe Fieber und starke Kopfschmerzen.', 'Welche Beschwerden haben Sie?', 'Verstehe.'),
      crit('since', 'Say since when', ['seit', 'tagen', 'gestern', 'woche'], 'Seit … Tagen.', 'Seit zwei Tagen.', 'Seit wann haben Sie das?', 'Hm, zwei Tage schon.'),
      crit('meds', 'Answer about medication', ['keine medikamente', 'ibuprofen', 'paracetamol', 'nehme', 'nichts genommen'], 'Ich nehme … / Ich nehme keine Medikamente.', 'Ich habe gestern eine Paracetamol genommen.', 'Nehmen Sie Medikamente?', 'Gut zu wissen.'),
      crit('note', 'Ask for a sick note', ['krankmeldung', 'krankschreibung', 'arbeitgeber', 'attest', 'krankgeschrieben'], 'Ich brauche eine Krankmeldung für meinen Arbeitgeber.', 'Könnte ich bitte eine Krankmeldung bekommen?', 'Brauchen Sie sonst noch etwas?', 'Natürlich, ich schreibe Sie bis Freitag krank.'),
    ],
    closingLine: 'Viel trinken und ausruhen. Gute Besserung!',
  },

  // ───────────────────────────── AIRPORT ─────────────────────────────
  {
    slug: 'airport-check-in',
    lang: 'de',
    env: 'airport',
    character: 'sara-checkin',
    title: 'Airport Check-in',
    description: 'Check in for your flight, drop your bag and ask for a window seat.',
    objective: 'Show your passport, check in your suitcase, ask for a window seat and the gate.',
    scenario: 'Frankfurt Airport, Terminal 1. The flight to Lisbon leaves in two hours.',
    level: 'A2',
    difficulty: 2,
    skills: ['SPEAKING', 'LISTENING'],
    minutes: 5,
    keyPhrases: [['der Reisepass', 'the passport'], ['der Koffer', 'the suitcase'], ['ein Fensterplatz', 'a window seat'], ['das Gate', 'the gate'], ['das Handgepäck', 'hand luggage']],
    grammarFocus: 'Akkusativ and polite questions',
    opening: 'Guten Tag! Ihren Reisepass, bitte. Wohin fliegen Sie heute?',
    criteria: [
      crit('destination', 'Say where you are flying', ['lissabon', 'nach', 'fliege'], 'Ich fliege nach …', 'Ich fliege nach Lissabon. Hier ist mein Pass.', 'Wohin geht die Reise?', 'Lissabon, wunderbar.'),
      crit('bag', 'Check in your suitcase', ['koffer', 'gepack', 'aufgeben', 'ein koffer'], 'Ich möchte einen Koffer aufgeben.', 'Ich möchte einen Koffer aufgeben.', 'Haben Sie Gepäck zum Aufgeben?', 'Stellen Sie ihn bitte aufs Band. 18 Kilo, perfekt.'),
      crit('seat', 'Ask for a window seat', ['fensterplatz', 'fenster', 'gang', 'platz'], 'Könnte ich einen Fensterplatz bekommen?', 'Könnte ich bitte einen Fensterplatz haben?', 'Haben Sie einen Sitzplatzwunsch?', 'Ja, 23A ist noch frei.'),
      crit('gate', 'Ask about the gate', ['gate', 'wann', 'boarding', 'abflug'], 'Von welchem Gate fliegen wir?', 'Von welchem Gate geht der Flug?', 'Noch eine Frage?', 'Gate B42, Boarding ist um 10:35.'),
    ],
    closingLine: 'Hier ist Ihre Bordkarte. Guten Flug!',
  },
  {
    slug: 'lost-luggage',
    lang: 'de',
    env: 'airport',
    character: 'sara-checkin',
    title: 'Lost Luggage',
    description: 'Your suitcase did not arrive. Report it and describe it in detail.',
    objective: 'Report the missing bag, describe it, give your contact details and ask what happens next.',
    scenario: 'Baggage claim in Hamburg. The belt has stopped. The learner\'s suitcase is missing.',
    level: 'B1',
    difficulty: 3,
    skills: ['SPEAKING', 'VOCABULARY'],
    minutes: 7,
    keyPhrases: [['Mein Koffer ist nicht angekommen.', "My suitcase didn't arrive."], ['Er ist dunkelblau und hat Rollen.', 'It is dark blue and has wheels.'], ['die Verlustanzeige', 'the lost baggage report'], ['Wie lange dauert das?', 'How long does it take?']],
    grammarFocus: 'Adjective endings and relative clauses',
    opening: 'Guten Tag, Gepäckermittlung. Wie kann ich Ihnen helfen?',
    criteria: [
      crit('report', 'Report the missing suitcase', ['nicht angekommen', 'fehlt', 'verloren', 'nicht da', 'koffer'], 'Mein Koffer ist nicht angekommen.', 'Mein Koffer ist leider nicht angekommen.', 'Was ist passiert?', 'Das tut mir leid. Welcher Flug war das?'),
      crit('describe', 'Describe it in detail', ['blau', 'schwarz', 'rot', 'grau', 'gross', 'klein', 'rollen', 'aufkleber', 'marke'], 'Er ist … und hat …', 'Er ist dunkelblau, ziemlich groß und hat einen gelben Aufkleber.', 'Wie sieht der Koffer aus?', 'Gut, das notiere ich.'),
      crit('contact', 'Give your contact details / address', ['adresse', 'hotel', 'telefonnummer', 'nummer', 'email', 'wohne'], 'Sie können mich unter … erreichen.', 'Ich wohne im Hotel Alsterblick, meine Nummer ist 0176 …', 'Wohin sollen wir den Koffer liefern?', 'Perfekt, wir liefern ihn direkt dorthin.'),
      crit('next', 'Ask what happens next / how long', ['wie lange', 'wann', 'was passiert', 'entschadigung', 'kosten'], 'Wie lange dauert das? / Was passiert jetzt?', 'Wie lange dauert das ungefähr?', 'Haben Sie noch Fragen?', 'Meistens kommt er innerhalb von 24 Stunden mit dem nächsten Flug.'),
    ],
    closingLine: 'Hier ist Ihre Vorgangsnummer. Wir melden uns so schnell wie möglich!',
  },

  // ───────────────────────────── WORKPLACE ─────────────────────────────
  {
    slug: 'first-day-at-work',
    lang: 'de',
    env: 'workplace',
    character: 'markus-colleague',
    title: 'First Day at Work',
    description: 'Your first day in a new team. Get to know your colleague and the office.',
    objective: 'Introduce yourself, talk about your role and ask two practical questions.',
    scenario: 'A start-up office in Hamburg. Markus shows the learner around.',
    level: 'A2',
    difficulty: 2,
    skills: ['SPEAKING', 'LISTENING'],
    minutes: 6,
    keyPhrases: [['Ich bin die/der Neue.', "I'm the new one."], ['Ich arbeite im Bereich …', 'I work in …'], ['Wo ist die Kaffeemaschine?', "Where's the coffee machine?"], ['Wann ist Mittagspause?', "When is lunch break?"]],
    grammarFocus: 'Duzen at work, W-questions, prepositions of place',
    opening: 'Hey, du musst die Neue oder der Neue sein! Ich bin Markus. Willkommen im Team!',
    criteria: [
      crit('intro', 'Introduce yourself', ['ich bin', 'ich heisse', 'freut mich', 'mein name'], 'Hallo, ich bin … Freut mich!', 'Hallo Markus, ich bin Leyla. Freut mich!', 'Wie heißt du?', 'Freut mich auch!'),
      crit('role', 'Say what your role is', ['ich arbeite', 'entwickler', 'marketing', 'design', 'vertrieb', 'bereich', 'team', 'als'], 'Ich arbeite als … / im Bereich …', 'Ich arbeite als Designerin im Produktteam.', 'Und was machst du hier genau?', 'Ah, dann arbeiten wir oft zusammen!'),
      crit('practical', 'Ask practical questions (coffee, lunch, desk)', ['kaffee', 'mittagspause', 'mittag', 'schreibtisch', 'toilette', 'kuche', 'wo ist', 'wann'], 'Wo ist …? / Wann ist …?', 'Wann ist hier normalerweise Mittagspause?', 'Hast du schon Fragen?', 'Meistens so um halb eins. Wir gehen oft zusammen zum Italiener um die Ecke.'),
    ],
    closingLine: 'So, das hier ist dein Platz. Wenn du was brauchst – ich sitze gleich daneben!',
  },
  {
    slug: 'difficult-customer',
    lang: 'de',
    env: 'workplace',
    character: 'frau-klein',
    title: 'The Difficult Customer',
    description: 'A customer is angry because her order is late. Resolve the complaint professionally.',
    objective: 'Calm the customer, apologise, find out the details and offer a solution.',
    scenario: 'Customer service phone line of an online furniture shop. Frau Klein\'s sofa is two weeks late.',
    level: 'B1',
    difficulty: 3,
    skills: ['SPEAKING', 'GRAMMAR'],
    minutes: 8,
    keyPhrases: [['Das tut mir sehr leid.', "I'm very sorry."], ['Ich verstehe Ihren Ärger.', 'I understand your frustration.'], ['Darf ich Ihre Bestellnummer haben?', 'May I have your order number?'], ['Ich schlage vor, …', 'I suggest …'], ['als Entschädigung', 'as compensation']],
    grammarFocus: 'Konjunktiv II and polite register (Sie)',
    opening: 'Endlich erreiche ich jemanden! Mein Sofa sollte vor zwei Wochen kommen. Was ist da los?',
    criteria: [
      crit('empathy', 'Apologise and show understanding', ['tut mir leid', 'entschuldigung', 'verstehe', 'argerlich', 'nachvollziehen'], 'Das tut mir sehr leid. Ich verstehe Ihren Ärger.', 'Das tut mir wirklich leid, Frau Klein. Ich verstehe Ihren Ärger.', 'Verstehen Sie überhaupt, wie ärgerlich das ist?', 'Na ja … danke, dass Sie das sagen.'),
      crit('details', 'Ask for the order number / details', ['bestellnummer', 'nummer', 'wann bestellt', 'name'], 'Darf ich Ihre Bestellnummer haben?', 'Darf ich bitte Ihre Bestellnummer haben?', 'Was brauchen Sie von mir?', 'Die Nummer ist 4471-B.'),
      crit('solution', 'Offer a concrete solution', ['ich schlage vor', 'konnen wir', 'lieferung', 'morgen', 'diese woche', 'liefern', 'termin'], 'Ich schlage vor, dass … / Wir könnten …', 'Ich schlage vor, dass wir das Sofa am Donnerstag liefern.', 'Und wie wollen Sie das jetzt lösen?', 'Donnerstag ginge … aber ich bin sauer.'),
      crit('compensation', 'Offer compensation', ['entschadigung', 'gutschein', 'rabatt', 'prozent', 'kostenlos', 'gratis'], 'Als Entschädigung bieten wir Ihnen … an.', 'Als Entschädigung bekommen Sie 15 % Rabatt.', 'Und was bekomme ich für den Ärger?', 'Okay, das ist fair. Danke.'),
    ],
    closingLine: 'Gut, dann warte ich auf Donnerstag. Danke für Ihre Hilfe.',
  },
  {
    slug: 'rescheduling-a-meeting',
    lang: 'de',
    env: 'workplace',
    character: 'markus-colleague',
    title: 'Rescheduling a Meeting',
    description: 'Convince your colleague to move tomorrow\'s meeting.',
    objective: 'Explain why you need to move it, suggest a new time and agree.',
    scenario: 'The weekly team meeting is tomorrow at 9:00, but the learner has a doctor\'s appointment.',
    level: 'B1',
    difficulty: 3,
    skills: ['SPEAKING'],
    minutes: 6,
    keyPhrases: [['Könnten wir das Meeting verschieben?', 'Could we move the meeting?'], ['Mir passt … besser.', '… suits me better.'], ['Wie wäre es mit …?', 'How about …?'], ['Einverstanden.', 'Agreed.']],
    grammarFocus: 'Konjunktiv II, weil-clauses, time expressions',
    opening: 'Morgen um neun steht das Team-Meeting, oder? Ich hab schon die Präsentation vorbereitet.',
    criteria: [
      crit('ask', 'Ask to move the meeting', ['verschieben', 'verlegen', 'andere zeit', 'spater'], 'Könnten wir das Meeting verschieben?', 'Könnten wir das Meeting vielleicht verschieben?', 'Gibt es ein Problem mit morgen?', 'Hm, warum denn?'),
      crit('reason', 'Give a reason (weil)', ['weil', 'termin', 'arzt', 'denn'], '…, weil ich einen Arzttermin habe.', 'Weil ich morgen früh einen Arzttermin habe.', 'Was ist der Grund?', 'Ah okay, das geht natürlich vor.'),
      crit('propose', 'Suggest a new time', ['wie ware es', 'nachmittag', 'uhr', 'donnerstag', 'mittwoch', 'freitag', 'passt'], 'Wie wäre es mit … um … Uhr?', 'Wie wäre es mit morgen Nachmittag um 15 Uhr?', 'Wann würde es dir passen?', 'Um 15 Uhr passt mir gut.'),
    ],
    closingLine: 'Alles klar, ich schicke eine neue Einladung. Gute Besserung schon mal!',
  },

  // ───────────────────────────── UNIVERSITY ─────────────────────────────
  {
    slug: 'university-enrolment',
    lang: 'de',
    env: 'university',
    character: 'prof-yilmaz',
    title: 'Talking to Your Lecturer',
    description: 'Ask your lecturer about the exam and a deadline extension.',
    objective: 'Introduce yourself, ask about the exam format and request more time for an assignment.',
    scenario: 'Office hour at the university. Prof. Yılmaz has ten minutes.',
    level: 'A2',
    difficulty: 2,
    skills: ['SPEAKING', 'GRAMMAR'],
    minutes: 6,
    keyPhrases: [['die Sprechstunde', 'office hour'], ['die Prüfung', 'the exam'], ['die Abgabe', 'the submission'], ['mehr Zeit', 'more time'], ['Wäre es möglich …?', 'Would it be possible …?']],
    grammarFocus: 'Formal register and modal verbs',
    opening: 'Kommen Sie herein. Was kann ich für Sie tun?',
    criteria: [
      crit('intro', 'Introduce yourself and your course', ['ich bin', 'ich heisse', 'seminar', 'kurs', 'student'], 'Ich bin … aus Ihrem Seminar …', 'Guten Tag, ich bin Omar aus Ihrem Seminar Statistik.', 'Sind Sie in meinem Seminar?', 'Ah ja, ich erinnere mich.'),
      crit('exam', 'Ask about the exam', ['prufung', 'klausur', 'test', 'mundlich', 'schriftlich'], 'Wie ist die Prüfung? Schriftlich oder mündlich?', 'Ist die Prüfung schriftlich oder mündlich?', 'Haben Sie Fragen zur Prüfung?', 'Schriftlich, 90 Minuten.'),
      crit('extension', 'Ask for more time for an assignment', ['mehr zeit', 'verlangern', 'spater abgeben', 'ware es moglich', 'abgabe'], 'Wäre es möglich, die Arbeit später abzugeben?', 'Wäre es möglich, die Hausarbeit eine Woche später abzugeben?', 'Noch etwas?', 'Eine Woche ist in Ordnung – schicken Sie mir bitte eine kurze E-Mail.'),
    ],
    closingLine: 'Viel Erfolg bei der Vorbereitung!',
  },
  {
    slug: 'group-project',
    lang: 'de',
    env: 'university',
    character: 'mia-friend',
    title: 'The Group Project',
    description: 'Organise a group project with a classmate who keeps changing the plan.',
    objective: 'Divide the tasks, agree on a deadline and handle disagreement politely.',
    scenario: 'University library café. Mia wants to start tomorrow; the deadline is in a week.',
    level: 'B1',
    difficulty: 3,
    skills: ['SPEAKING'],
    minutes: 7,
    keyPhrases: [['Ich schlage vor, dass …', 'I suggest that …'], ['Du übernimmst …', 'You take over …'], ['bis Freitag', 'by Friday'], ['Da bin ich anderer Meinung.', 'I see it differently.']],
    grammarFocus: 'dass-clauses, future with werden',
    opening: 'Okay, Präsentation über erneuerbare Energien. Wie machen wir das?',
    criteria: [
      crit('tasks', 'Divide the tasks', ['ich ubernehme', 'du ubernimmst', 'ich mache', 'du machst', 'aufteilen', 'recherche', 'folien'], 'Ich übernehme …, und du …', 'Ich übernehme die Recherche, und du machst die Folien.', 'Wer macht was?', 'Gute Idee, Folien kann ich gut.'),
      crit('deadline', 'Agree on an internal deadline', ['bis', 'freitag', 'montag', 'deadline', 'termin', 'treffen'], 'Wollen wir das bis … fertig haben?', 'Lass uns bis Freitag alles fertig haben.', 'Bis wann sollten wir fertig sein?', 'Freitag klingt gut.'),
      crit('disagree', 'Politely disagree with Mia\'s idea', ['anderer meinung', 'ich finde', 'besser', 'aber', 'nicht so gut', 'stimmt nicht'], 'Da bin ich anderer Meinung, weil …', 'Ich finde, das ist keine gute Idee, weil wir zu wenig Zeit haben.', 'Ich würde eigentlich lieber alles am letzten Tag machen – das klappt immer!', 'Hm, okay, du hast vielleicht recht.'),
    ],
    closingLine: 'Okay, Team! Dann bis Freitag.',
  },

  // ───────────────────────────── GOVERNMENT OFFICE ─────────────────────────────
  {
    slug: 'registering-your-address',
    lang: 'de',
    env: 'government-office',
    character: 'herr-braun',
    title: 'Registering Your Address',
    description: 'The Anmeldung: register your new address at the citizens\' office.',
    objective: 'Explain why you are here, hand over the documents and understand what happens next.',
    scenario: 'Bürgeramt Berlin-Mitte. The learner has an appointment at 10:20. Herr Braun is strict but helpful.',
    level: 'A2',
    difficulty: 2,
    skills: ['SPEAKING', 'LISTENING'],
    minutes: 6,
    keyPhrases: [['Ich möchte mich anmelden.', 'I would like to register.'], ['die Wohnungsgeberbestätigung', 'landlord confirmation'], ['der Reisepass', 'the passport'], ['die Meldebescheinigung', 'registration certificate']],
    grammarFocus: 'Reflexive verbs (sich anmelden), formal register',
    opening: 'Guten Tag. Ihre Wartenummer? … Gut. Worum geht es?',
    criteria: [
      crit('purpose', 'Say why you are here', ['anmelden', 'anmeldung', 'neue adresse', 'umgezogen'], 'Ich möchte mich anmelden.', 'Ich möchte mich anmelden. Ich bin neu in Berlin.', 'Was möchten Sie erledigen?', 'Gut. Haben Sie die Unterlagen dabei?'),
      crit('documents', 'Hand over your documents', ['pass', 'reisepass', 'ausweis', 'wohnungsgeberbestatigung', 'formular', 'unterlagen', 'hier ist'], 'Hier ist mein Pass und die Wohnungsgeberbestätigung.', 'Hier sind mein Reisepass und die Wohnungsgeberbestätigung.', 'Ich brauche Ihren Pass und die Wohnungsgeberbestätigung.', 'Danke. Moment bitte …'),
      crit('next', 'Ask what happens next', ['bescheinigung', 'was passiert', 'brauche ich', 'noch etwas', 'fertig', 'steuer'], 'Brauche ich sonst noch etwas? / Bekomme ich eine Bescheinigung?', 'Bekomme ich eine Meldebescheinigung?', 'Haben Sie noch Fragen?', 'Ja, hier ist Ihre Meldebescheinigung. Die Steuer-ID kommt per Post.'),
    ],
    closingLine: 'Fertig. Auf Wiedersehen – und willkommen in Berlin.',
  },
  {
    slug: 'residence-permit',
    lang: 'de',
    env: 'government-office',
    character: 'herr-braun',
    title: 'The Residence Permit Appointment',
    description: 'Extend your residence permit and clarify a missing document.',
    objective: 'Explain your situation, react to the missing document and agree on next steps.',
    scenario: 'Foreigners\' office. Your permit expires in a month; one document is missing.',
    level: 'B1',
    difficulty: 4,
    skills: ['SPEAKING', 'LISTENING'],
    minutes: 8,
    keyPhrases: [['den Aufenthaltstitel verlängern', 'to extend the residence permit'], ['der Arbeitsvertrag', 'employment contract'], ['nachreichen', 'to submit later'], ['eine Fiktionsbescheinigung', 'provisional permit']],
    grammarFocus: 'Passive (wird bearbeitet), indirect questions',
    opening: 'Guten Tag. Sie möchten Ihren Aufenthaltstitel verlängern? Ich sehe, der Arbeitsvertrag fehlt.',
    criteria: [
      crit('situation', 'Explain your situation', ['verlangern', 'lauft ab', 'monat', 'arbeite', 'aufenthaltstitel'], 'Mein Aufenthaltstitel läuft in … ab.', 'Mein Aufenthaltstitel läuft nächsten Monat ab, deshalb bin ich hier.', 'Wann läuft Ihr Titel ab?', 'Verstehe.'),
      crit('missing', 'React to the missing document', ['nachreichen', 'per email', 'schicken', 'vergessen', 'bringe', 'morgen'], 'Kann ich den Vertrag nachreichen?', 'Kann ich den Arbeitsvertrag per E-Mail nachreichen?', 'Wie wollen Sie das mit dem Vertrag machen?', 'Ja, per E-Mail innerhalb von zwei Wochen.'),
      crit('meanwhile', 'Ask about your status in the meantime (indirect question)', ['ob ich', 'wissen ob', 'in der zwischenzeit', 'fiktionsbescheinigung', 'darf ich weiter'], 'Können Sie mir sagen, ob ich weiter arbeiten darf?', 'Können Sie mir sagen, ob ich in der Zwischenzeit weiter arbeiten darf?', 'Gibt es noch etwas?', 'Ja, Sie bekommen eine Fiktionsbescheinigung.'),
    ],
    closingLine: 'Hier ist Ihre Fiktionsbescheinigung. Wir melden uns.',
  },

  // ───────────────────────────── SOCIAL LIFE ─────────────────────────────
  {
    slug: 'weekend-plans',
    lang: 'de',
    env: 'social-life',
    character: 'mia-friend',
    title: 'Making Weekend Plans',
    description: 'Plan something fun with Mia for Saturday.',
    objective: 'Suggest an activity, agree on a time and a meeting point.',
    scenario: 'Text-message style chat. Mia is bored and wants to do something on Saturday.',
    level: 'A2',
    difficulty: 2,
    skills: ['SPEAKING', 'WRITING'],
    minutes: 5,
    keyPhrases: [['Hast du Lust, …?', 'Do you feel like …?'], ['Wollen wir …?', 'Shall we …?'], ['Treffen wir uns um …?', 'Shall we meet at …?'], ['Das klingt super!', 'Sounds great!']],
    grammarFocus: 'Modal verbs and time expressions',
    opening: 'Heyyy! Hast du am Samstag schon was vor? Mir ist so langweilig 😩',
    criteria: [
      crit('suggest', 'Suggest an activity', ['hast du lust', 'wollen wir', 'kino', 'museum', 'park', 'essen', 'konzert', 'flohmarkt', 'schwimmen', 'wandern'], 'Hast du Lust, … zu …? / Wollen wir …?', 'Hast du Lust, auf den Flohmarkt zu gehen?', 'Was wollen wir machen?', 'Oh ja, voll gute Idee!'),
      crit('time', 'Agree on a time', ['uhr', 'vormittag', 'nachmittag', 'abend', 'morgens', 'mittag'], 'Um … Uhr?', 'Um elf Uhr?', 'Wann passt es dir?', 'Elf ist perfekt.'),
      crit('place', 'Agree on a meeting point', ['treffen', 'vor dem', 'am bahnhof', 'bei mir', 'bei dir', 'u-bahn', 'eingang'], 'Treffen wir uns am/vor dem …?', 'Treffen wir uns an der U-Bahn-Station?', 'Wo treffen wir uns?', 'Deal! Ich freu mich 😊'),
    ],
    closingLine: 'Bis Samstag! 🎉',
  },
  {
    slug: 'discussing-a-film',
    lang: 'de',
    env: 'social-life',
    character: 'mia-friend',
    title: 'Discussing a Film',
    description: 'You just watched a film with Mia. She loved it — you did not.',
    objective: 'Give your opinion with reasons, react to Mia\'s view and find something you agree on.',
    scenario: 'Leaving the cinema. Mia is enthusiastic about the film; the learner found it boring.',
    level: 'B1',
    difficulty: 3,
    skills: ['SPEAKING'],
    minutes: 6,
    keyPhrases: [['Meiner Meinung nach …', 'In my opinion …'], ['Mir hat … (nicht) gefallen.', 'I (didn\'t) like …'], ['Da hast du recht.', "You're right."], ['Einerseits …, andererseits …', 'On the one hand …, on the other hand …']],
    grammarFocus: 'Präteritum of common verbs, opinion phrases',
    opening: 'Wow, war das nicht der beste Film des Jahres?!',
    criteria: [
      crit('opinion', 'Give your opinion', ['meiner meinung nach', 'ich finde', 'ich fand', 'langweilig', 'nicht so gut', 'gefallen'], 'Meiner Meinung nach war der Film …', 'Ehrlich gesagt fand ich ihn ziemlich langweilig.', 'Wie fandest du ihn?', 'Echt jetzt? Warum denn?'),
      crit('reason', 'Give a reason', ['weil', 'denn', 'zu lang', 'geschichte', 'schauspieler', 'ende'], '…, weil die Geschichte …', 'Weil die Geschichte zu vorhersehbar war.', 'Was genau hat dir nicht gefallen?', 'Hm, okay, das Ende war schon klar.'),
      crit('agree', 'Find something you agree on', ['da hast du recht', 'stimmt', 'einerseits', 'aber die musik', 'gut fand ich', 'immerhin'], 'Da hast du recht – aber … / Einerseits …', 'Aber da hast du recht: Die Musik war wirklich toll.', 'Gab es denn gar nichts Gutes?', 'Siehst du! Die Musik war der Hammer.'),
    ],
    closingLine: 'Nächstes Mal darfst du den Film aussuchen 😄',
  },

  // ───────────────────────────── TRAVEL ─────────────────────────────
  {
    slug: 'renting-a-car',
    lang: 'de',
    env: 'travel',
    character: 'anna-reception',
    title: 'Renting a Car',
    description: 'Rent a car for a road trip and understand the insurance options.',
    objective: 'Say what car you need, ask about insurance and clarify the fuel policy.',
    scenario: 'Car rental desk at Munich airport.',
    level: 'B1',
    difficulty: 3,
    skills: ['SPEAKING', 'LISTENING'],
    minutes: 6,
    keyPhrases: [['ein kleines Auto', 'a small car'], ['die Vollkaskoversicherung', 'comprehensive insurance'], ['die Selbstbeteiligung', 'the excess'], ['vollgetankt zurückgeben', 'return with a full tank']],
    grammarFocus: 'Comparatives and conditional wenn-clauses',
    opening: 'Guten Tag! Haben Sie online reserviert oder möchten Sie ein Auto mieten?',
    criteria: [
      crit('car', 'Say what car you need and for how long', ['auto', 'kleines', 'grosses', 'tage', 'woche', 'automatik'], 'Ich brauche ein … Auto für … Tage.', 'Ich brauche ein kleines Auto mit Automatik für fünf Tage.', 'Was für ein Auto brauchen Sie?', 'Da habe ich einen VW Polo.'),
      crit('insurance', 'Ask about insurance', ['versicherung', 'vollkasko', 'selbstbeteiligung', 'unfall'], 'Was ist in der Versicherung enthalten?', 'Wie hoch ist die Selbstbeteiligung?', 'Möchten Sie eine Versicherung dazu?', 'Mit Vollkasko ohne Selbstbeteiligung kostet es 12 Euro mehr pro Tag.'),
      crit('fuel', 'Clarify the fuel policy', ['tanken', 'vollgetankt', 'benzin', 'tank'], 'Muss ich das Auto vollgetankt zurückgeben?', 'Muss ich das Auto vollgetankt zurückbringen?', 'Noch Fragen?', 'Ja, voll abholen, voll zurückgeben.'),
    ],
    closingLine: 'Hier sind die Schlüssel. Gute Fahrt!',
  },

  // ───────────────────────────── BUSINESS ─────────────────────────────
  {
    slug: 'job-interview',
    lang: 'de',
    env: 'business',
    character: 'dr-neumann',
    title: 'The Job Interview',
    description: 'A real interview for a position you want. Present yourself convincingly.',
    objective: 'Present your experience, explain your motivation, handle a weakness question and ask a question yourself.',
    scenario: 'Video interview with Dr. Neumann, HR manager of a logistics company in Hamburg.',
    level: 'B1',
    difficulty: 4,
    skills: ['SPEAKING', 'GRAMMAR'],
    minutes: 10,
    xp: 150,
    keyPhrases: [['Ich habe … Jahre Erfahrung in …', 'I have … years of experience in …'], ['Mich interessiert besonders …', 'I am particularly interested in …'], ['Eine meiner Schwächen ist …', 'One of my weaknesses is …'], ['Ich arbeite daran, …', "I'm working on …"]],
    grammarFocus: 'Perfekt/Präteritum for experience, dass-clauses',
    opening: 'Schön, dass es geklappt hat. Erzählen Sie doch mal etwas über sich und Ihre Erfahrung.',
    criteria: [
      crit('experience', 'Present your experience', ['erfahrung', 'gearbeitet', 'jahre', 'ich war', 'studium', 'ausbildung'], 'Ich habe … Jahre Erfahrung in … / Ich habe bei … gearbeitet.', 'Ich habe fünf Jahre Erfahrung in der Logistik und habe zuletzt bei DHL gearbeitet.', 'Was haben Sie bisher gemacht?', 'Das klingt sehr relevant.'),
      crit('motivation', 'Explain your motivation', ['interessiert', 'motiviert', 'weil', 'mochte', 'ihr unternehmen', 'stelle'], 'Mich interessiert besonders …, weil …', 'Mich interessiert die Stelle besonders, weil Sie international arbeiten.', 'Warum möchten Sie gerade bei uns arbeiten?', 'Schön, dass Sie das sagen.'),
      crit('weakness', 'Answer the weakness question constructively', ['schwache', 'arbeite daran', 'manchmal', 'perfektionist', 'ungeduldig', 'verbessern'], 'Eine meiner Schwächen ist …, aber ich arbeite daran.', 'Ich bin manchmal ungeduldig, aber ich arbeite daran.', 'Was würden Sie als Ihre Schwäche bezeichnen?', 'Eine ehrliche Antwort, danke.'),
      crit('question', 'Ask the interviewer a question', ['ich habe eine frage', 'wie sieht', 'team', 'einarbeitung', 'homeoffice', 'nachste schritt'], 'Darf ich auch eine Frage stellen? Wie sieht …?', 'Wie sieht die Einarbeitung in den ersten Wochen aus?', 'Haben Sie noch Fragen an uns?', 'Gute Frage! Sie bekommen einen Mentor für die ersten drei Monate.'),
    ],
    closingLine: 'Vielen Dank für das Gespräch. Sie hören bis Ende der Woche von uns.',
  },
  {
    slug: 'presenting-a-project',
    lang: 'de',
    env: 'business',
    character: 'dr-neumann',
    title: 'Presenting Your Project',
    description: 'Present a project update to management and handle critical questions.',
    objective: 'Structure the presentation, present a result with numbers, and respond to criticism.',
    scenario: 'Quarterly review meeting. Dr. Neumann represents management and is sceptical about the budget.',
    level: 'B2',
    difficulty: 4,
    skills: ['SPEAKING', 'VOCABULARY'],
    minutes: 10,
    xp: 150,
    keyPhrases: [['Zunächst möchte ich …', 'First I would like to …'], ['Wie Sie sehen, …', 'As you can see …'], ['im Vergleich zum Vorjahr', 'compared to last year'], ['Das ist ein berechtigter Einwand.', 'That is a valid objection.']],
    grammarFocus: 'Nominalisation, presentation connectors',
    opening: 'Bitte, Sie haben das Wort. Wir haben allerdings nur zehn Minuten.',
    criteria: [
      crit('structure', 'Open with a clear structure', ['zunachst', 'zuerst', 'danach', 'abschliessend', 'agenda', 'drei punkte'], 'Zunächst …, danach …, abschließend …', 'Zunächst stelle ich die Ergebnisse vor, danach die nächsten Schritte.', 'Wie ist Ihre Präsentation aufgebaut?', 'Gut, klar strukturiert.'),
      crit('result', 'Present a result with numbers', ['prozent', 'gestiegen', 'gesunken', 'im vergleich', 'umsatz', 'kosten'], 'Wie Sie sehen, ist … um … Prozent gestiegen.', 'Wie Sie sehen, ist der Umsatz im Vergleich zum Vorjahr um 18 Prozent gestiegen.', 'Was sind die wichtigsten Zahlen?', 'Beeindruckend – aber das Budget wurde überschritten.'),
      crit('objection', 'Respond to the criticism professionally', ['berechtigter einwand', 'verstehe', 'allerdings', 'jedoch', 'investition', 'langfristig'], 'Das ist ein berechtigter Einwand. Allerdings …', 'Das ist ein berechtigter Einwand. Allerdings zahlt sich die Investition langfristig aus.', 'Wie erklären Sie die Budgetüberschreitung?', 'Gut argumentiert. Das überzeugt mich.'),
    ],
    closingLine: 'Danke für die Präsentation. Wir besprechen das Budget nächste Woche.',
  },
  {
    slug: 'salary-negotiation',
    lang: 'de',
    env: 'business',
    character: 'dr-neumann',
    title: 'Negotiating Your Salary',
    description: 'You got the offer — now negotiate a better salary and conditions.',
    objective: 'Thank, state your expectation with arguments, negotiate a compromise.',
    scenario: 'Final call with Dr. Neumann. The offer is 52,000 € a year; the learner hopes for 58,000 €.',
    level: 'B2',
    difficulty: 5,
    skills: ['SPEAKING', 'GRAMMAR'],
    minutes: 10,
    xp: 150,
    keyPhrases: [['Ich freue mich sehr über das Angebot.', "I'm very pleased with the offer."], ['Meine Gehaltsvorstellung liegt bei …', 'My salary expectation is …'], ['Angesichts meiner Erfahrung …', 'Given my experience …'], ['Wären Sie bereit, …?', 'Would you be willing to …?']],
    grammarFocus: 'Konjunktiv II, genitive prepositions (angesichts, aufgrund)',
    opening: 'Wir würden Sie sehr gerne einstellen. Unser Angebot liegt bei 52.000 Euro im Jahr. Was sagen Sie?',
    criteria: [
      crit('thanks', 'Thank and show interest', ['freue mich', 'danke', 'vielen dank', 'angebot'], 'Ich freue mich sehr über das Angebot.', 'Vielen Dank, ich freue mich sehr über das Angebot.', 'Wie klingt das für Sie?', 'Das freut uns.'),
      crit('expectation', 'State your expectation with an argument', ['gehaltsvorstellung', 'angesichts', 'aufgrund', 'erfahrung', '58', 'marktublich'], 'Angesichts meiner Erfahrung liegt meine Gehaltsvorstellung bei …', 'Angesichts meiner Erfahrung liegt meine Gehaltsvorstellung bei 58.000 Euro.', 'Was wäre Ihre Vorstellung?', 'Hm, das ist deutlich mehr als geplant.'),
      crit('compromise', 'Negotiate a compromise', ['waren sie bereit', 'kompromiss', 'homeoffice', 'weiterbildung', 'bonus', 'treffen uns', 'mitte'], 'Wären Sie bereit, …? / Könnten wir uns bei … treffen?', 'Wären Sie bereit, sich bei 55.000 Euro plus einem Weiterbildungsbudget zu treffen?', 'Was könnten Sie sich als Kompromiss vorstellen?', '55.000 und 1.500 Euro Weiterbildung – damit kann ich leben.'),
    ],
    closingLine: 'Dann schicke ich Ihnen den Vertrag morgen zu. Willkommen an Bord!',
  },
];

// ───────────────────────────── CHAOS MODE ─────────────────────────────
export const CHAOS_DE: MissionDef[] = [
  {
    slug: 'chaos-travel-day',
    lang: 'de',
    env: 'airport',
    character: 'sara-checkin',
    mode: 'CHAOS',
    title: 'Chaos: Travel Day',
    description: 'Something will go wrong on your trip. You don\'t know what. Handle it.',
    objective: 'Understand the unexpected problem, explain your needs and get a concrete solution.',
    scenario: 'A travel day that does not go to plan.',
    level: 'A2',
    difficulty: 3,
    skills: ['SPEAKING', 'LISTENING'],
    minutes: 7,
    xp: 120,
    keyPhrases: [['Was ist passiert?', 'What happened?'], ['Was kann ich jetzt machen?', 'What can I do now?'], ['Ich brauche …', 'I need …'], ['Gibt es eine Alternative?', 'Is there an alternative?']],
    grammarFocus: 'Questions, modal verbs, Perfekt',
    opening: 'Entschuldigung, darf ich kurz stören?',
    criteria: [
      crit('understand', 'Find out what exactly happened', ['was ist passiert', 'warum', 'was bedeutet', 'wieso', 'verstehe nicht', 'wie bitte'], 'Was ist passiert? / Warum …?', 'Was ist passiert? Warum geht das nicht?', 'Haben Sie verstanden, was los ist?', 'Ich erkläre es Ihnen gern noch einmal.'),
      crit('need', 'Explain what you need', ['ich brauche', 'ich muss', 'wichtig', 'termin', 'heute noch', 'weil'], 'Ich brauche … / Ich muss heute noch …', 'Ich muss heute noch in München sein, weil ich morgen arbeite.', 'Was ist für Sie jetzt am wichtigsten?', 'Okay, das verstehe ich.'),
      crit('solution', 'Get a concrete solution', ['alternative', 'andere', 'nachste', 'hotel', 'gutschein', 'umbuchen', 'erstatten', 'losung'], 'Gibt es eine Alternative? / Können Sie … umbuchen?', 'Können Sie mich auf den nächsten Flug umbuchen?', 'Was schlagen Sie vor?', 'Gut, so machen wir es.'),
    ],
    closingLine: 'Puh – geschafft! Gute Weiterreise.',
    extra: {
      twists: [
        { title: 'Flight cancelled', situation: 'Your flight to Munich has just been cancelled because of a storm.', openingLine: 'Es tut mir leid, Ihr Flug nach München wurde gerade wegen eines Sturms gestrichen.' },
        { title: 'Hotel booking lost', situation: 'You arrive at your hotel, but they cannot find your reservation and are fully booked.', openingLine: 'Hm, ich finde leider keine Reservierung auf Ihren Namen. Und wir sind heute komplett ausgebucht.' },
        { title: 'Phone stolen', situation: 'Your phone was just stolen at the station. A police officer approaches you.', openingLine: 'Guten Tag, Polizei. Sie sehen aufgeregt aus – ist Ihnen etwas gestohlen worden?' },
        { title: 'Wrong order delivered', situation: 'The taxi you booked took you to the wrong airport terminal 20 minutes before boarding.', openingLine: 'So, Terminal 2, wir sind da! Das macht 34 Euro.' },
        { title: 'Unexpected call', situation: 'Your boss calls: an important client is coming tomorrow and you must change your travel plans.', openingLine: 'Hallo, hier ist Frau Berg. Gut, dass ich Sie erreiche – wir haben ein Problem mit morgen.' },
      ],
    },
  },
  {
    slug: 'chaos-at-work',
    lang: 'de',
    env: 'workplace',
    character: 'markus-colleague',
    mode: 'CHAOS',
    title: 'Chaos: A Day at the Office',
    description: 'A normal workday — until it isn\'t.',
    objective: 'Stay calm, clarify the situation and agree on what to do.',
    scenario: 'An ordinary Tuesday at the office.',
    level: 'B1',
    difficulty: 4,
    skills: ['SPEAKING'],
    minutes: 8,
    xp: 130,
    keyPhrases: [['Keine Panik.', "Don't panic."], ['Lass uns überlegen, …', "Let's think about …"], ['Ich kümmere mich darum.', "I'll take care of it."], ['Bis wann brauchst du …?', 'By when do you need …?']],
    grammarFocus: 'Konjunktiv II and imperatives',
    opening: 'Hey, hast du kurz Zeit? Wir haben ein Problem.',
    criteria: [
      crit('clarify', 'Clarify what is going on', ['was ist los', 'was genau', 'was ist passiert', 'erzahl', 'warum'], 'Was ist genau passiert?', 'Okay, keine Panik. Was ist genau passiert?', 'Willst du wissen, was los ist?', 'Also, hör zu …'),
      crit('plan', 'Propose a plan', ['lass uns', 'ich schlage vor', 'wir konnten', 'ich kummere mich', 'zuerst'], 'Lass uns … / Ich kümmere mich um …', 'Ich schlage vor, dass ich den Kunden anrufe und du die Unterlagen vorbereitest.', 'Was machen wir jetzt?', 'Gute Idee, so machen wir es.'),
      crit('deadline', 'Agree on timing', ['bis', 'uhr', 'heute', 'morgen', 'wann'], 'Bis wann muss das fertig sein?', 'Bis wann muss das fertig sein?', 'Wie viel Zeit haben wir?', 'Bis 16 Uhr. Das schaffen wir!'),
    ],
    closingLine: 'Danke, ohne dich wäre das schiefgegangen!',
    extra: {
      twists: [
        { title: 'Server down', situation: 'The company website is down right before a big product launch.', openingLine: 'Die Website ist komplett down – und in zwei Stunden ist der Launch!' },
        { title: 'Angry client', situation: 'A major client just called and threatened to cancel the contract.', openingLine: 'Herr Fischer von Müller AG hat angerufen. Er will den Vertrag kündigen!' },
        { title: 'Surprise presentation', situation: 'The boss wants you to present the project to the board in one hour.', openingLine: 'Die Chefin will, dass DU in einer Stunde das Projekt dem Vorstand präsentierst.' },
        { title: 'Unexpected interview', situation: 'A journalist is at reception and wants a statement about your product.', openingLine: 'Am Empfang steht eine Journalistin und will ein Interview zum neuen Produkt.' },
      ],
    },
  },
];

// ───────────────────────────── STORY MODE ─────────────────────────────
export const STORY_DE = {
  slug: 'new-in-berlin',
  title: 'New in Berlin',
  description: 'Six chapters, one new life. Your choices shape the story.',
  level: 'A2' as const,
};

export const STORY_CHAPTERS_DE: MissionDef[] = [
  {
    slug: 'story-berlin-1', lang: 'de', env: 'train-station', character: 'jonas-passenger', mode: 'STORY', story: 'new-in-berlin', chapter: 1,
    title: 'Chapter 1 — Arrival', description: 'You arrive at Berlin Hauptbahnhof with two suitcases and no plan.',
    objective: 'Ask for help, find out how to get to your temporary room and get on your way.',
    scenario: 'Berlin main station, late afternoon. The learner just arrived to start a new life.',
    level: 'A2', difficulty: 2, skills: ['SPEAKING', 'LISTENING'], minutes: 6, xp: 120,
    keyPhrases: [['Ich bin gerade angekommen.', 'I just arrived.'], ['Wie komme ich nach …?', 'How do I get to …?'], ['die U-Bahn', 'the underground'], ['eine Fahrkarte', 'a ticket']],
    grammarFocus: 'Perfekt with sein', opening: 'Brauchst du Hilfe? Du siehst aus, als wärst du gerade erst angekommen.',
    criteria: [
      crit('arrived', 'Say you just arrived', ['angekommen', 'neu', 'gerade', 'erste mal'], 'Ja, ich bin gerade angekommen.', 'Ja, ich bin gerade angekommen. Ich bin neu in Berlin.', 'Bist du neu hier?', 'Willkommen in Berlin!'),
      crit('where', 'Say where you need to go', ['neukolln', 'kreuzberg', 'wedding', 'adresse', 'strasse', 'nach'], 'Ich muss nach …', 'Ich muss nach Neukölln, in die Weserstraße.', 'Wo musst du hin?', 'Ah, Neukölln. Da nimmst du am besten die U7.'),
      crit('ticket', 'Ask about the ticket', ['fahrkarte', 'ticket', 'kaufen', 'automat'], 'Wo kann ich eine Fahrkarte kaufen?', 'Wo kann ich eine Fahrkarte kaufen?', 'Hast du schon ein Ticket?', 'Am Automaten da drüben – nimm ein AB-Ticket.'),
    ],
    closingLine: 'Viel Glück in deinem neuen Leben!',
    extra: { choices: [{ id: 'ask-local', label: 'Ask a local for help', consequence: 'You meet Jonas, who becomes a friend.' }, { id: 'go-alone', label: 'Try to find the way alone', consequence: 'You get a little lost, but learn the city.' }] },
  },
  {
    slug: 'story-berlin-2', lang: 'de', env: 'home', character: 'herr-schulz', mode: 'STORY', story: 'new-in-berlin', chapter: 2,
    title: 'Chapter 2 — The Apartment Viewing', description: 'You found an apartment ad. The landlord has ten other applicants.',
    objective: 'Ask about rent and conditions and convince the landlord to choose you.',
    scenario: 'An apartment viewing in Neukölln. Herr Schulz is choosing between many applicants.',
    level: 'A2', difficulty: 3, skills: ['SPEAKING'], minutes: 7, xp: 120,
    keyPhrases: [['die Kaltmiete', 'rent without utilities'], ['die Nebenkosten', 'utilities'], ['die Kaution', 'deposit'], ['Ich bin zuverlässig.', 'I am reliable.']],
    grammarFocus: 'W-questions and adjectives', opening: 'So, das ist die Wohnung. 55 Quadratmeter. Haben Sie Fragen?',
    criteria: [
      crit('rent', 'Ask about the rent', ['miete', 'kostet', 'kaltmiete', 'warmmiete', 'nebenkosten'], 'Wie hoch ist die Miete?', 'Wie hoch ist die Warmmiete?', 'Wollen Sie etwas zu den Kosten wissen?', '850 Euro warm, plus drei Monatsmieten Kaution.'),
      crit('conditions', 'Ask about a condition (move-in, pets, deposit)', ['einziehen', 'ab wann', 'kaution', 'haustiere', 'frei'], 'Ab wann ist die Wohnung frei?', 'Ab wann ist die Wohnung frei?', 'Noch Fragen?', 'Ab dem ersten des nächsten Monats.'),
      crit('convince', 'Convince him to choose you', ['zuverlassig', 'arbeite', 'unbefristet', 'ruhig', 'nichtraucher', 'gehalt'], 'Ich bin zuverlässig und habe einen festen Job.', 'Ich habe einen unbefristeten Job und bin sehr ruhig.', 'Warum sollte ich gerade Sie nehmen?', 'Hm, das klingt gut. Ich melde mich morgen.'),
    ],
    closingLine: 'Schicken Sie mir bitte noch Ihre Unterlagen.',
    extra: { choices: [{ id: 'honest', label: 'Be completely honest about your situation', consequence: 'Herr Schulz appreciates honesty.' }, { id: 'impress', label: 'Try to impress him', consequence: 'You sound confident — maybe too confident.' }] },
  },
  {
    slug: 'story-berlin-3', lang: 'de', env: 'workplace', character: 'markus-colleague', mode: 'STORY', story: 'new-in-berlin', chapter: 3,
    title: 'Chapter 3 — The New Job', description: 'Your first week in a Berlin start-up.',
    objective: 'Talk about your role, ask for help with a task and make lunch plans.',
    scenario: 'Monday morning. Markus is your onboarding buddy.',
    level: 'A2', difficulty: 3, skills: ['SPEAKING'], minutes: 6, xp: 120,
    keyPhrases: [['Kannst du mir helfen?', 'Can you help me?'], ['Ich verstehe … nicht.', "I don't understand …"], ['Gehen wir zusammen essen?', 'Shall we have lunch together?']],
    grammarFocus: 'Modal verbs, du-form', opening: 'Na, wie war dein erster Morgen? Kommst du mit dem Tool klar?',
    criteria: [
      crit('feeling', 'Say how your first morning went', ['gut', 'spannend', 'viel', 'anstrengend', 'neu'], 'Gut, aber …', 'Gut, aber noch alles sehr neu.', 'Und, wie ist es bisher?', 'Das ist normal am Anfang.'),
      crit('help', 'Ask for help with something specific', ['kannst du mir helfen', 'verstehe nicht', 'wie funktioniert', 'zeigen'], 'Kannst du mir … zeigen?', 'Kannst du mir zeigen, wie das Ticketsystem funktioniert?', 'Brauchst du Hilfe?', 'Klar, schau mal hier …'),
      crit('lunch', 'Make lunch plans', ['mittag', 'essen', 'zusammen', 'mittagspause'], 'Gehen wir zusammen Mittag essen?', 'Gehen wir nachher zusammen Mittag essen?', 'Hast du schon Pläne für die Pause?', 'Gerne! Um eins?'),
    ],
    closingLine: 'Willkommen im Team – du machst das super!',
    extra: { choices: [{ id: 'team-lunch', label: 'Join the team lunch', consequence: 'You meet the whole team.' }, { id: 'focus', label: 'Stay and finish your task', consequence: 'Your boss notices your focus.' }] },
  },
  {
    slug: 'story-berlin-4', lang: 'de', env: 'social-life', character: 'mia-friend', mode: 'STORY', story: 'new-in-berlin', chapter: 4,
    title: 'Chapter 4 — New People', description: 'Mia invites you to a party where you know nobody.',
    objective: 'Start a conversation, talk about yourself and arrange to meet again.',
    scenario: 'A rooftop party in Friedrichshain. Music, strangers, a beautiful view.',
    level: 'A2', difficulty: 3, skills: ['SPEAKING', 'LISTENING'], minutes: 6, xp: 120,
    keyPhrases: [['Woher kennst du Mia?', 'How do you know Mia?'], ['Was machst du so?', 'What do you do?'], ['Wollen wir Nummern tauschen?', 'Shall we swap numbers?']],
    grammarFocus: 'Questions, du-form small talk', opening: 'Hi! Ich bin Elif. Woher kennst du Mia?',
    criteria: [
      crit('connection', 'Say how you know Mia', ['kurs', 'sprachkurs', 'arbeit', 'kennen', 'uber'], 'Wir kennen uns aus …', 'Wir kennen uns aus dem Sprachkurs.', 'Woher kennt ihr euch?', 'Ah cool!'),
      crit('about', 'Tell something about yourself', ['ich bin', 'ich arbeite', 'ich komme', 'seit', 'wohne'], 'Ich bin seit … in Berlin und …', 'Ich bin seit zwei Monaten in Berlin und arbeite in einem Start-up.', 'Und was machst du so?', 'Spannend!'),
      crit('meet-again', 'Arrange to meet again', ['nummer', 'treffen', 'wiedersehen', 'instagram', 'nachste woche'], 'Wollen wir Nummern tauschen?', 'Wollen wir Nummern tauschen? Dann können wir mal was trinken gehen.', 'Wir sollten uns mal wieder sehen!', 'Auf jeden Fall!'),
    ],
    closingLine: 'Schön, dich kennengelernt zu haben!',
    extra: { choices: [{ id: 'stay-late', label: 'Stay until the end', consequence: 'You make three new friends.' }, { id: 'leave-early', label: 'Leave early — work tomorrow', consequence: 'You are fresh for the big day.' }] },
  },
  {
    slug: 'story-berlin-5', lang: 'de', env: 'home', character: 'frau-weber', mode: 'STORY', story: 'new-in-berlin', chapter: 5,
    title: 'Chapter 5 — A Problem Occurs', description: 'Water is coming through Frau Weber\'s ceiling — from your apartment.',
    objective: 'Apologise, explain and agree with your neighbour on what to do.',
    scenario: 'Late evening. Your washing machine leaked. Frau Weber knocks at your door.',
    level: 'B1', difficulty: 3, skills: ['SPEAKING'], minutes: 7, xp: 130,
    keyPhrases: [['Das tut mir furchtbar leid.', "I'm terribly sorry."], ['die Waschmaschine', 'the washing machine'], ['die Versicherung', 'the insurance'], ['Ich bezahle den Schaden.', "I'll pay for the damage."]],
    grammarFocus: 'Konjunktiv II and Perfekt', opening: 'Entschuldigen Sie die Störung, aber bei mir tropft Wasser von der Decke!',
    criteria: [
      crit('apologise', 'Apologise sincerely', ['tut mir leid', 'entschuldigung', 'furchtbar'], 'Das tut mir furchtbar leid!', 'Oh nein, das tut mir furchtbar leid!', 'Wissen Sie, was passiert ist?', 'Na ja, Unfälle passieren.'),
      crit('explain', 'Explain what happened', ['waschmaschine', 'kaputt', 'ausgelaufen', 'schlauch', 'wasser'], 'Meine Waschmaschine ist ausgelaufen.', 'Meine Waschmaschine ist ausgelaufen – der Schlauch war kaputt.', 'Was ist denn passiert?', 'Ach so, die Waschmaschine.'),
      crit('solution', 'Agree on next steps', ['versicherung', 'bezahle', 'handwerker', 'vermieter', 'morgen', 'helfen'], 'Ich rufe meine Versicherung an und … ', 'Ich melde es meiner Haftpflichtversicherung und rufe morgen den Vermieter an.', 'Was machen wir jetzt?', 'Danke, das ist sehr verantwortungsvoll.'),
    ],
    closingLine: 'Na gut. Kommen Sie doch morgen auf einen Tee vorbei, dann besprechen wir alles.',
    extra: { choices: [{ id: 'insurance', label: 'Call your insurance immediately', consequence: 'Everything gets solved quickly.' }, { id: 'fix-yourself', label: 'Try to fix it yourself first', consequence: 'Frau Weber is impressed — but sceptical.' }] },
  },
  {
    slug: 'story-berlin-6', lang: 'de', env: 'business', character: 'dr-neumann', mode: 'STORY', story: 'new-in-berlin', chapter: 6,
    title: 'Chapter 6 — The Big Decision', description: 'You get a job offer in Munich. Stay in Berlin or start again?',
    objective: 'Discuss the offer, weigh pros and cons and announce your decision.',
    scenario: 'Dr. Neumann from a Munich company calls with an offer that would change everything.',
    level: 'B1', difficulty: 4, skills: ['SPEAKING'], minutes: 8, xp: 150,
    keyPhrases: [['Einerseits …, andererseits …', 'On the one hand … on the other hand …'], ['Ich habe mich entschieden, …', 'I have decided …'], ['Das ist mir wichtig.', 'That matters to me.']],
    grammarFocus: 'Connectors and infinitive clauses with zu', opening: 'Wir würden Sie sehr gerne in München sehen. Haben Sie schon über unser Angebot nachgedacht?',
    criteria: [
      crit('questions', 'Ask about the offer', ['gehalt', 'umzug', 'homeoffice', 'team', 'ab wann'], 'Wie sieht es mit … aus?', 'Wie sieht es mit Homeoffice und Umzugskosten aus?', 'Haben Sie Fragen zum Angebot?', 'Zwei Tage Homeoffice, und wir zahlen den Umzug.'),
      crit('weigh', 'Weigh pros and cons', ['einerseits', 'andererseits', 'aber', 'vorteil', 'nachteil', 'freunde'], 'Einerseits …, andererseits …', 'Einerseits ist das Angebot toll, andererseits habe ich hier meine Freunde.', 'Was spricht für und was gegen München?', 'Das verstehe ich gut.'),
      crit('decide', 'Announce your decision', ['entschieden', 'nehme', 'bleibe', 'annehmen', 'ablehnen'], 'Ich habe mich entschieden, …', 'Ich habe mich entschieden, das Angebot anzunehmen.', 'Und, wie entscheiden Sie sich?', 'Eine mutige Entscheidung – wir respektieren das.'),
    ],
    closingLine: 'Egal wie – Sie haben in diesem Jahr unglaublich viel geschafft.',
    extra: { choices: [{ id: 'lean-stay', label: 'You are leaning towards staying', consequence: 'Berlin is home now.' }, { id: 'lean-go', label: 'You are leaning towards going', consequence: 'A new adventure begins.' }] },
  },
];

// ───────────────────────────── DEBATE MODE ─────────────────────────────
export const DEBATE_DE: MissionDef[] = [
  {
    slug: 'debate-remote-work', lang: 'de', env: 'business', character: 'lukas-debater', mode: 'DEBATE',
    title: 'Debate: Should People Work Remotely?', description: 'Lukas thinks everyone should be back in the office. Argue the other side.',
    objective: 'Defend remote work with at least two arguments, react to a counter-argument and conclude.',
    scenario: 'A structured debate. The AI argues against remote work; the learner argues for it.',
    level: 'B1', difficulty: 4, skills: ['SPEAKING', 'GRAMMAR'], minutes: 8, xp: 150,
    keyPhrases: [['Meiner Meinung nach …', 'In my opinion …'], ['Ein wichtiges Argument ist, dass …', 'An important argument is that …'], ['Das sehe ich anders, weil …', 'I see it differently because …'], ['Zusammenfassend …', 'In summary …']],
    grammarFocus: 'dass/weil clauses, argument connectors', opening: 'Ich bin überzeugt: Homeoffice schadet Teams. Menschen arbeiten im Büro einfach besser zusammen. Was sagen Sie?',
    criteria: [
      crit('argument1', 'Give your first argument', ['meiner meinung nach', 'ein argument', 'zeit', 'pendeln', 'flexibel', 'produktiv'], 'Meiner Meinung nach …, weil …', 'Meiner Meinung nach sind Menschen zu Hause produktiver, weil sie nicht pendeln müssen.', 'Haben Sie überhaupt ein Argument?', 'Hm, das Pendeln – okay, ein Punkt für Sie.'),
      crit('counter', 'Respond to the counter-argument', ['das sehe ich anders', 'stimmt nicht', 'zwar', 'aber', 'allerdings', 'videokonferenz', 'tools'], 'Das sehe ich anders, weil …', 'Das sehe ich anders: Mit guten Tools funktioniert Teamarbeit auch online.', 'Aber Zusammenarbeit leidet doch!', 'Interessant, aber nicht jeder kann das.'),
      crit('argument2', 'Give a second argument', ['ausserdem', 'zudem', 'familie', 'umwelt', 'kosten', 'gesundheit', 'zweitens'], 'Außerdem …', 'Außerdem ist es besser für die Umwelt, weil weniger Menschen Auto fahren.', 'Gibt es noch weitere Gründe?', 'Die Umwelt – zugegeben, das ist stark.'),
      crit('conclude', 'Conclude', ['zusammenfassend', 'insgesamt', 'deshalb', 'abschliessend', 'fazit'], 'Zusammenfassend …', 'Zusammenfassend bin ich überzeugt, dass Homeoffice für die meisten Jobs besser ist.', 'Und Ihr Fazit?', 'Gut argumentiert. Ich bin fast überzeugt.'),
    ],
    closingLine: 'Ein starkes Plädoyer. Unentschieden – mit leichtem Vorteil für Sie!',
    extra: { stance: 'Against remote work: offices are better for collaboration, culture and learning.', topic: 'Remote work' },
  },
  {
    slug: 'debate-car-free-city', lang: 'de', env: 'city', character: 'lukas-debater', mode: 'DEBATE',
    title: 'Debate: Car-Free City Centres', description: 'Lukas wants to ban cars from the city centre. Do you agree?',
    objective: 'Take a position, give reasons, react to his arguments and conclude.',
    scenario: 'Local radio debate about banning cars from the old town.',
    level: 'B2', difficulty: 5, skills: ['SPEAKING', 'VOCABULARY'], minutes: 10, xp: 150,
    keyPhrases: [['Ich bin dafür/dagegen, dass …', "I'm for/against …"], ['Einerseits …, andererseits …', 'On the one hand … on the other …'], ['Das mag stimmen, jedoch …', 'That may be true, however …'], ['Lebensqualität', 'quality of life']],
    grammarFocus: 'Concessive clauses (obwohl, zwar … aber), nominalisation', opening: 'Autos haben in der Innenstadt nichts verloren. Ein komplettes Verbot würde die Lebensqualität enorm steigern. Sehen Sie das nicht auch so?',
    criteria: [
      crit('position', 'Take a clear position', ['ich bin dafur', 'ich bin dagegen', 'meiner ansicht', 'ich finde'], 'Ich bin dagegen, dass …', 'Ich bin dagegen, dass Autos komplett verboten werden.', 'Wofür oder wogegen sind Sie?', 'Interessant – und warum?'),
      crit('concession', 'Concede a point, then counter (zwar … aber / obwohl)', ['zwar', 'obwohl', 'das mag stimmen', 'jedoch', 'allerdings'], 'Das mag stimmen, jedoch … / Zwar …, aber …', 'Zwar wäre die Luft besser, aber viele Geschäfte würden Kunden verlieren.', 'Geben Sie zu, dass die Luft besser wäre?', 'Ein fairer Punkt.'),
      crit('example', 'Support with an example or evidence', ['zum beispiel', 'beispielsweise', 'studie', 'in kopenhagen', 'in paris', 'statistik'], 'Zum Beispiel …', 'Zum Beispiel haben in einigen Städten kleine Läden nach dem Verbot geschlossen.', 'Haben Sie Belege?', 'Das muss man sich genauer ansehen.'),
      crit('conclude', 'Conclude with a compromise or summary', ['kompromiss', 'zusammenfassend', 'insgesamt', 'losung', 'stattdessen'], 'Ein Kompromiss wäre …', 'Ein guter Kompromiss wären autofreie Sonntage und besserer Nahverkehr.', 'Was wäre Ihre Lösung?', 'Ein kluger Vorschlag.'),
    ],
    closingLine: 'Danke für diese lebhafte Debatte!',
    extra: { stance: 'For a complete car ban in city centres: health, climate and quality of life outweigh inconvenience.', topic: 'Car-free city centres' },
  },
  {
    slug: 'debate-social-media', lang: 'de', env: 'social-life', character: 'lukas-debater', mode: 'DEBATE',
    title: 'Debate: Social Media for Teenagers', description: 'Should social media be banned for under-16s?',
    objective: 'Argue your view with two reasons and respond to his challenge.',
    scenario: 'A podcast discussion about teenagers and social media.',
    level: 'B1', difficulty: 4, skills: ['SPEAKING'], minutes: 8, xp: 140,
    keyPhrases: [['Ich bin der Meinung, dass …', 'I am of the opinion that …'], ['Erstens … zweitens …', 'Firstly … secondly …'], ['Das überzeugt mich nicht.', "That doesn't convince me."]],
    grammarFocus: 'dass-clauses and ordinal connectors', opening: 'Soziale Medien sind für Jugendliche völlig harmlos. Ein Verbot wäre lächerlich. Oder?',
    criteria: [
      crit('view', 'State your view', ['ich bin der meinung', 'ich finde', 'meiner meinung'], 'Ich bin der Meinung, dass …', 'Ich bin der Meinung, dass soziale Medien für Jugendliche gefährlich sein können.', 'Was denken Sie?', 'Gefährlich? Das ist übertrieben.'),
      crit('reasons', 'Give two reasons', ['erstens', 'zweitens', 'ausserdem', 'weil', 'sucht', 'mobbing', 'schlaf'], 'Erstens …, zweitens …', 'Erstens macht es süchtig, zweitens gibt es viel Cybermobbing.', 'Welche Gründe haben Sie?', 'Okay, Mobbing ist ein echtes Problem.'),
      crit('rebut', 'Rebut his challenge', ['uberzeugt mich nicht', 'das stimmt nicht', 'aber', 'trotzdem', 'jedoch'], 'Das überzeugt mich nicht, weil …', 'Das überzeugt mich nicht, weil Studien das Gegenteil zeigen.', 'Aber Jugendliche brauchen das für ihr Sozialleben!', 'Hm, Sie haben gute Argumente.'),
    ],
    closingLine: 'Spannende Diskussion – danke!',
    extra: { stance: 'Social media is harmless for teenagers and an important part of their social life.', topic: 'Social media and teenagers' },
  },
];
