import type { Level } from './types';

/** [word, article, plural, translation, category, level, example, partOfSpeech] */
type Row = [string, string | null, string | null, string, string, Level, string, string];

const DE: Row[] = [
  // A1 — café & food
  ['Kaffee', 'der', 'Kaffees', 'coffee', 'food & drink', 'A1', 'Ich hätte gern einen Kaffee.', 'noun'],
  ['Tee', 'der', 'Tees', 'tea', 'food & drink', 'A1', 'Einen Tee mit Zitrone, bitte.', 'noun'],
  ['Wasser', 'das', null, 'water', 'food & drink', 'A1', 'Ein Glas Wasser, bitte.', 'noun'],
  ['Milch', 'die', null, 'milk', 'food & drink', 'A1', 'Mit Milch, bitte.', 'noun'],
  ['Zucker', 'der', null, 'sugar', 'food & drink', 'A1', 'Ohne Zucker, danke.', 'noun'],
  ['Kuchen', 'der', 'Kuchen', 'cake', 'food & drink', 'A1', 'Der Kuchen ist sehr lecker.', 'noun'],
  ['Brot', 'das', 'Brote', 'bread', 'food & drink', 'A1', 'Ich kaufe ein Brot.', 'noun'],
  ['Brötchen', 'das', 'Brötchen', 'bread roll', 'food & drink', 'A1', 'Zwei Brötchen, bitte.', 'noun'],
  ['Apfel', 'der', 'Äpfel', 'apple', 'food & drink', 'A1', 'Der Apfel ist rot.', 'noun'],
  ['Saft', 'der', 'Säfte', 'juice', 'food & drink', 'A1', 'Einen Orangensaft, bitte.', 'noun'],
  ['Rechnung', 'die', 'Rechnungen', 'bill', 'café & restaurant', 'A1', 'Die Rechnung, bitte.', 'noun'],
  ['Speisekarte', 'die', 'Speisekarten', 'menu', 'café & restaurant', 'A1', 'Kann ich die Speisekarte haben?', 'noun'],
  ['Tisch', 'der', 'Tische', 'table', 'café & restaurant', 'A1', 'Ist der Tisch frei?', 'noun'],
  ['bezahlen', null, null, 'to pay', 'café & restaurant', 'A1', 'Ich möchte bezahlen.', 'verb'],
  ['bestellen', null, null, 'to order', 'café & restaurant', 'A1', 'Ich möchte bestellen.', 'verb'],
  ['lecker', null, null, 'tasty', 'café & restaurant', 'A1', 'Das ist sehr lecker!', 'adjective'],
  ['Cappuccino', 'der', 'Cappuccinos', 'cappuccino', 'food & drink', 'A1', 'Einen Cappuccino, bitte.', 'noun'],
  ['Apfelstrudel', 'der', 'Apfelstrudel', 'apple strudel', 'food & drink', 'A1', 'Ich nehme einen Apfelstrudel.', 'noun'],
  ['Croissant', 'das', 'Croissants', 'croissant', 'food & drink', 'A1', 'Ein Croissant, bitte.', 'noun'],
  ['Bon', 'der', 'Bons', 'receipt', 'café & restaurant', 'A1', 'Hier ist Ihr Bon.', 'noun'],
  // A1 — people & basics
  ['Familie', 'die', 'Familien', 'family', 'people', 'A1', 'Meine Familie wohnt in Marokko.', 'noun'],
  ['Freund', 'der', 'Freunde', 'friend', 'people', 'A1', 'Das ist mein Freund Tom.', 'noun'],
  ['Kind', 'das', 'Kinder', 'child', 'people', 'A1', 'Sie hat zwei Kinder.', 'noun'],
  ['Name', 'der', 'Namen', 'name', 'basics', 'A1', 'Mein Name ist Sara.', 'noun'],
  ['Land', 'das', 'Länder', 'country', 'basics', 'A1', 'Aus welchem Land kommen Sie?', 'noun'],
  ['Stadt', 'die', 'Städte', 'city', 'city', 'A1', 'Berlin ist eine große Stadt.', 'noun'],
  ['Straße', 'die', 'Straßen', 'street', 'city', 'A1', 'Ich wohne in der Hauptstraße.', 'noun'],
  ['Wohnung', 'die', 'Wohnungen', 'apartment', 'home', 'A1', 'Die Wohnung ist hell.', 'noun'],
  ['Haus', 'das', 'Häuser', 'house', 'home', 'A1', 'Das Haus ist alt.', 'noun'],
  ['Zimmer', 'das', 'Zimmer', 'room', 'home', 'A1', 'Mein Zimmer ist klein.', 'noun'],
  ['Arbeit', 'die', 'Arbeiten', 'work', 'work', 'A1', 'Ich gehe zur Arbeit.', 'noun'],
  ['Zeit', 'die', 'Zeiten', 'time', 'basics', 'A1', 'Hast du Zeit?', 'noun'],
  ['Tag', 'der', 'Tage', 'day', 'time', 'A1', 'Guten Tag!', 'noun'],
  ['Woche', 'die', 'Wochen', 'week', 'time', 'A1', 'Nächste Woche habe ich Urlaub.', 'noun'],
  ['Uhr', 'die', 'Uhren', 'clock / o\'clock', 'time', 'A1', 'Es ist acht Uhr.', 'noun'],
  ['heute', null, null, 'today', 'time', 'A1', 'Heute ist Montag.', 'adverb'],
  ['morgen', null, null, 'tomorrow', 'time', 'A1', 'Bis morgen!', 'adverb'],
  ['gestern', null, null, 'yesterday', 'time', 'A1', 'Gestern war ich müde.', 'adverb'],
  ['sprechen', null, null, 'to speak', 'basics', 'A1', 'Ich spreche ein bisschen Deutsch.', 'verb'],
  ['wohnen', null, null, 'to live', 'basics', 'A1', 'Ich wohne in Berlin.', 'verb'],
  ['arbeiten', null, null, 'to work', 'work', 'A1', 'Ich arbeite im Krankenhaus.', 'verb'],
  ['kommen', null, null, 'to come', 'basics', 'A1', 'Ich komme aus Syrien.', 'verb'],
  ['gehen', null, null, 'to go', 'basics', 'A1', 'Wir gehen ins Kino.', 'verb'],
  ['kaufen', null, null, 'to buy', 'shopping', 'A1', 'Ich kaufe Brot.', 'verb'],
  ['brauchen', null, null, 'to need', 'basics', 'A1', 'Ich brauche Hilfe.', 'verb'],
  ['groß', null, null, 'big', 'basics', 'A1', 'Das Zimmer ist groß.', 'adjective'],
  ['klein', null, null, 'small', 'basics', 'A1', 'Ein kleiner Kaffee, bitte.', 'adjective'],
  ['teuer', null, null, 'expensive', 'shopping', 'A1', 'Das ist zu teuer.', 'adjective'],
  ['billig', null, null, 'cheap', 'shopping', 'A1', 'Das T-Shirt ist billig.', 'adjective'],
  ['links', null, null, 'left', 'directions', 'A1', 'Gehen Sie links.', 'adverb'],
  ['rechts', null, null, 'right', 'directions', 'A1', 'Dann rechts.', 'adverb'],
  ['geradeaus', null, null, 'straight ahead', 'directions', 'A1', 'Immer geradeaus.', 'adverb'],
  ['Bahnhof', 'der', 'Bahnhöfe', 'train station', 'travel', 'A1', 'Wo ist der Bahnhof?', 'noun'],
  ['Zug', 'der', 'Züge', 'train', 'travel', 'A1', 'Der Zug kommt um acht.', 'noun'],
  ['Fahrkarte', 'die', 'Fahrkarten', 'ticket', 'travel', 'A1', 'Eine Fahrkarte nach Hamburg, bitte.', 'noun'],
  ['Gleis', 'das', 'Gleise', 'platform', 'travel', 'A1', 'Der Zug fährt von Gleis 3.', 'noun'],
  ['Hotel', 'das', 'Hotels', 'hotel', 'travel', 'A1', 'Das Hotel ist im Zentrum.', 'noun'],
  ['Schlüssel', 'der', 'Schlüssel', 'key', 'home', 'A1', 'Hier ist Ihr Schlüssel.', 'noun'],
  ['Frühstück', 'das', 'Frühstücke', 'breakfast', 'food & drink', 'A1', 'Wann gibt es Frühstück?', 'noun'],
  ['Arzt', 'der', 'Ärzte', 'doctor', 'health', 'A1', 'Ich muss zum Arzt.', 'noun'],
  ['Apotheke', 'die', 'Apotheken', 'pharmacy', 'health', 'A1', 'Die Apotheke ist um die Ecke.', 'noun'],
  ['Kopfschmerzen', 'die', null, 'headache', 'health', 'A1', 'Ich habe Kopfschmerzen.', 'noun'],
  ['krank', null, null, 'sick', 'health', 'A1', 'Ich bin krank.', 'adjective'],
  ['Tablette', 'die', 'Tabletten', 'tablet', 'health', 'A1', 'Nehmen Sie eine Tablette.', 'noun'],
  ['Museum', 'das', 'Museen', 'museum', 'city', 'A1', 'Das Museum ist heute geöffnet.', 'noun'],
  ['Hobby', 'das', 'Hobbys', 'hobby', 'free time', 'A1', 'Mein Hobby ist Kochen.', 'noun'],
  ['Stock', 'der', 'Stockwerke', 'floor (storey)', 'home', 'A1', 'Ich wohne im dritten Stock.', 'noun'],
  ['Nachbar', 'der', 'Nachbarn', 'neighbour', 'people', 'A1', 'Mein Nachbar ist sehr nett.', 'noun'],
  ['Eier', 'die', null, 'eggs', 'food & drink', 'A1', 'Zehn Eier, bitte.', 'noun'],
  ['Preis', 'der', 'Preise', 'price', 'shopping', 'A1', 'Der Preis ist gut.', 'noun'],
  // A2
  ['Termin', 'der', 'Termine', 'appointment', 'everyday', 'A2', 'Ich habe morgen einen Termin.', 'noun'],
  ['Reservierung', 'die', 'Reservierungen', 'reservation', 'travel', 'A2', 'Ich habe eine Reservierung.', 'noun'],
  ['Verspätung', 'die', 'Verspätungen', 'delay', 'travel', 'A2', 'Der Zug hat Verspätung.', 'noun'],
  ['umsteigen', null, null, 'to change (trains)', 'travel', 'A2', 'In Köln müssen Sie umsteigen.', 'verb'],
  ['aussteigen', null, null, 'to get off', 'travel', 'A2', 'Ich steige hier aus.', 'verb'],
  ['Haltestelle', 'die', 'Haltestellen', 'stop', 'travel', 'A2', 'Die nächste Haltestelle ist Alexanderplatz.', 'noun'],
  ['Koffer', 'der', 'Koffer', 'suitcase', 'travel', 'A2', 'Mein Koffer ist schwer.', 'noun'],
  ['Reisepass', 'der', 'Reisepässe', 'passport', 'travel', 'A2', 'Ihren Reisepass, bitte.', 'noun'],
  ['Flughafen', 'der', 'Flughäfen', 'airport', 'travel', 'A2', 'Wie komme ich zum Flughafen?', 'noun'],
  ['Kollege', 'der', 'Kollegen', 'colleague', 'work', 'A2', 'Mein Kollege hilft mir.', 'noun'],
  ['Besprechung', 'die', 'Besprechungen', 'meeting', 'work', 'A2', 'Die Besprechung beginnt um zehn.', 'noun'],
  ['Mittagspause', 'die', 'Mittagspausen', 'lunch break', 'work', 'A2', 'Wann ist Mittagspause?', 'noun'],
  ['Erfahrung', 'die', 'Erfahrungen', 'experience', 'work', 'A2', 'Ich habe viel Erfahrung.', 'noun'],
  ['Miete', 'die', 'Mieten', 'rent', 'home', 'A2', 'Die Miete ist hoch.', 'noun'],
  ['Vermieter', 'der', 'Vermieter', 'landlord', 'home', 'A2', 'Ich rufe den Vermieter an.', 'noun'],
  ['Heizung', 'die', 'Heizungen', 'heating', 'home', 'A2', 'Die Heizung funktioniert nicht.', 'noun'],
  ['kaputt', null, null, 'broken', 'everyday', 'A2', 'Mein Handy ist kaputt.', 'adjective'],
  ['zurückgeben', null, null, 'to return (sth)', 'shopping', 'A2', 'Ich möchte das zurückgeben.', 'verb'],
  ['umtauschen', null, null, 'to exchange', 'shopping', 'A2', 'Kann ich das umtauschen?', 'verb'],
  ['Kassenbon', 'der', 'Kassenbons', 'receipt', 'shopping', 'A2', 'Haben Sie den Kassenbon?', 'noun'],
  ['Fieber', 'das', null, 'fever', 'health', 'A2', 'Ich habe Fieber.', 'noun'],
  ['Krankmeldung', 'die', 'Krankmeldungen', 'sick note', 'health', 'A2', 'Ich brauche eine Krankmeldung.', 'noun'],
  ['Anmeldung', 'die', 'Anmeldungen', 'registration', 'bureaucracy', 'A2', 'Die Anmeldung ist im Bürgeramt.', 'noun'],
  ['Formular', 'das', 'Formulare', 'form', 'bureaucracy', 'A2', 'Füllen Sie das Formular aus.', 'noun'],
  ['Unterlagen', 'die', null, 'documents', 'bureaucracy', 'A2', 'Haben Sie alle Unterlagen?', 'noun'],
  ['Prüfung', 'die', 'Prüfungen', 'exam', 'study', 'A2', 'Die Prüfung ist schwer.', 'noun'],
  ['verschieben', null, null, 'to postpone', 'work', 'A2', 'Können wir das Meeting verschieben?', 'verb'],
  ['vorschlagen', null, null, 'to suggest', 'everyday', 'A2', 'Ich schlage vor, dass wir gehen.', 'verb'],
  ['Lust haben', null, null, 'to feel like', 'free time', 'A2', 'Hast du Lust auf Kino?', 'phrase'],
  ['treffen', null, null, 'to meet', 'free time', 'A2', 'Wir treffen uns um acht.', 'verb'],
  ['Wetter', 'das', null, 'weather', 'everyday', 'A2', 'Das Wetter ist heute schön.', 'noun'],
  ['Urlaub', 'der', 'Urlaube', 'holiday', 'free time', 'A2', 'Wir fahren in den Urlaub.', 'noun'],
  ['Geschenk', 'das', 'Geschenke', 'gift', 'everyday', 'A2', 'Das ist ein Geschenk für dich.', 'noun'],
  ['Gesundheit', 'die', null, 'health', 'health', 'A2', 'Gesundheit ist wichtig.', 'noun'],
  ['Entschuldigung', 'die', 'Entschuldigungen', 'apology / excuse me', 'everyday', 'A2', 'Entschuldigung, wo ist der Ausgang?', 'noun'],
  ['bekommen', null, null, 'to receive', 'everyday', 'A2', 'Ich habe ein Paket bekommen.', 'verb'],
  ['vergessen', null, null, 'to forget', 'everyday', 'A2', 'Ich habe meinen Schlüssel vergessen.', 'verb'],
  ['erklären', null, null, 'to explain', 'everyday', 'A2', 'Kannst du mir das erklären?', 'verb'],
  ['Fensterplatz', 'der', 'Fensterplätze', 'window seat', 'travel', 'A2', 'Ich hätte gern einen Fensterplatz.', 'noun'],
  // B1
  ['Beschwerde', 'die', 'Beschwerden', 'complaint', 'work', 'B1', 'Ich habe eine Beschwerde.', 'noun'],
  ['Entschädigung', 'die', 'Entschädigungen', 'compensation', 'travel', 'B1', 'Bekomme ich eine Entschädigung?', 'noun'],
  ['Lösung', 'die', 'Lösungen', 'solution', 'work', 'B1', 'Wir finden eine Lösung.', 'noun'],
  ['Vorteil', 'der', 'Vorteile', 'advantage', 'opinion', 'B1', 'Ein Vorteil ist die Flexibilität.', 'noun'],
  ['Nachteil', 'der', 'Nachteile', 'disadvantage', 'opinion', 'B1', 'Der Nachteil ist der Preis.', 'noun'],
  ['Meinung', 'die', 'Meinungen', 'opinion', 'opinion', 'B1', 'Meiner Meinung nach ist das falsch.', 'noun'],
  ['überzeugen', null, null, 'to convince', 'opinion', 'B1', 'Das überzeugt mich nicht.', 'verb'],
  ['Vertrag', 'der', 'Verträge', 'contract', 'work', 'B1', 'Ich unterschreibe den Vertrag.', 'noun'],
  ['Bewerbung', 'die', 'Bewerbungen', 'application', 'work', 'B1', 'Ich schreibe eine Bewerbung.', 'noun'],
  ['Vorstellungsgespräch', 'das', 'Vorstellungsgespräche', 'job interview', 'work', 'B1', 'Morgen habe ich ein Vorstellungsgespräch.', 'noun'],
  ['Gehalt', 'das', 'Gehälter', 'salary', 'work', 'B1', 'Das Gehalt ist gut.', 'noun'],
  ['Aufenthaltstitel', 'der', 'Aufenthaltstitel', 'residence permit', 'bureaucracy', 'B1', 'Mein Aufenthaltstitel läuft ab.', 'noun'],
  ['verlängern', null, null, 'to extend', 'bureaucracy', 'B1', 'Ich möchte meinen Pass verlängern.', 'verb'],
  ['Versicherung', 'die', 'Versicherungen', 'insurance', 'everyday', 'B1', 'Haben Sie eine Versicherung?', 'noun'],
  ['Schaden', 'der', 'Schäden', 'damage', 'everyday', 'B1', 'Der Schaden ist groß.', 'noun'],
  ['dringend', null, null, 'urgent', 'everyday', 'B1', 'Es ist dringend.', 'adjective'],
  ['zuverlässig', null, null, 'reliable', 'work', 'B1', 'Sie ist sehr zuverlässig.', 'adjective'],
  ['Umwelt', 'die', null, 'environment', 'society', 'B1', 'Wir müssen die Umwelt schützen.', 'noun'],
  ['Gesellschaft', 'die', 'Gesellschaften', 'society', 'society', 'B1', 'Die Gesellschaft verändert sich.', 'noun'],
  ['Erfolg', 'der', 'Erfolge', 'success', 'work', 'B1', 'Viel Erfolg!', 'noun'],
  ['sich beschweren', null, null, 'to complain', 'everyday', 'B1', 'Ich möchte mich beschweren.', 'verb'],
  ['sich entscheiden', null, null, 'to decide', 'everyday', 'B1', 'Ich habe mich entschieden.', 'verb'],
  ['außerdem', null, null, 'furthermore', 'connectors', 'B1', 'Außerdem ist es billiger.', 'adverb'],
  ['trotzdem', null, null, 'nevertheless', 'connectors', 'B1', 'Es regnet, trotzdem gehe ich raus.', 'adverb'],
  ['deshalb', null, null, 'therefore', 'connectors', 'B1', 'Ich bin müde, deshalb bleibe ich zu Hause.', 'adverb'],
  ['Wasserschaden', 'der', 'Wasserschäden', 'water damage', 'home', 'B1', 'Wir haben einen Wasserschaden.', 'noun'],
  ['Kaution', 'die', 'Kautionen', 'deposit', 'home', 'B1', 'Die Kaution beträgt drei Monatsmieten.', 'noun'],
  ['Nebenkosten', 'die', null, 'utilities', 'home', 'B1', 'Die Nebenkosten sind inklusive.', 'noun'],
  ['Selbstbeteiligung', 'die', 'Selbstbeteiligungen', 'excess (insurance)', 'travel', 'B1', 'Wie hoch ist die Selbstbeteiligung?', 'noun'],
  ['Einarbeitung', 'die', null, 'onboarding', 'work', 'B1', 'Die Einarbeitung dauert zwei Wochen.', 'noun'],
  // B2
  ['Verhandlung', 'die', 'Verhandlungen', 'negotiation', 'business', 'B2', 'Die Verhandlung war erfolgreich.', 'noun'],
  ['Kompromiss', 'der', 'Kompromisse', 'compromise', 'business', 'B2', 'Wir haben einen Kompromiss gefunden.', 'noun'],
  ['Einwand', 'der', 'Einwände', 'objection', 'business', 'B2', 'Das ist ein berechtigter Einwand.', 'noun'],
  ['Umsatz', 'der', 'Umsätze', 'revenue', 'business', 'B2', 'Der Umsatz ist gestiegen.', 'noun'],
  ['Investition', 'die', 'Investitionen', 'investment', 'business', 'B2', 'Die Investition lohnt sich.', 'noun'],
  ['Nachhaltigkeit', 'die', null, 'sustainability', 'society', 'B2', 'Nachhaltigkeit ist uns wichtig.', 'noun'],
  ['Lebensqualität', 'die', null, 'quality of life', 'society', 'B2', 'Die Lebensqualität ist hoch.', 'noun'],
  ['Herausforderung', 'die', 'Herausforderungen', 'challenge', 'work', 'B2', 'Das ist eine große Herausforderung.', 'noun'],
  ['Voraussetzung', 'die', 'Voraussetzungen', 'prerequisite', 'work', 'B2', 'Deutschkenntnisse sind Voraussetzung.', 'noun'],
  ['Maßnahme', 'die', 'Maßnahmen', 'measure', 'society', 'B2', 'Die Regierung plant neue Maßnahmen.', 'noun'],
  ['Auswirkung', 'die', 'Auswirkungen', 'effect', 'society', 'B2', 'Welche Auswirkungen hat das?', 'noun'],
  ['angesichts', null, null, 'in view of', 'connectors', 'B2', 'Angesichts der Lage warten wir.', 'preposition'],
  ['hingegen', null, null, 'whereas / however', 'connectors', 'B2', 'Er ist ruhig, sie hingegen sehr lebhaft.', 'adverb'],
  ['infolgedessen', null, null, 'as a result', 'connectors', 'B2', 'Infolgedessen stiegen die Preise.', 'adverb'],
  ['berücksichtigen', null, null, 'to take into account', 'business', 'B2', 'Wir müssen alle Faktoren berücksichtigen.', 'verb'],
  ['gewährleisten', null, null, 'to guarantee', 'business', 'B2', 'Wir gewährleisten Qualität.', 'verb'],
  ['überzeugend', null, null, 'convincing', 'opinion', 'B2', 'Das Argument ist überzeugend.', 'adjective'],
  ['umstritten', null, null, 'controversial', 'opinion', 'B2', 'Das Thema ist umstritten.', 'adjective'],
  ['Stellungnahme', 'die', 'Stellungnahmen', 'statement', 'opinion', 'B2', 'Wir geben eine Stellungnahme ab.', 'noun'],
  ['Gehaltsvorstellung', 'die', 'Gehaltsvorstellungen', 'salary expectation', 'business', 'B2', 'Was ist Ihre Gehaltsvorstellung?', 'noun'],
  ['Weiterbildung', 'die', 'Weiterbildungen', 'further training', 'business', 'B2', 'Die Firma zahlt die Weiterbildung.', 'noun'],
  ['nachvollziehen', null, null, 'to comprehend', 'opinion', 'B2', 'Das kann ich gut nachvollziehen.', 'verb'],
];

const EN: Row[] = [
  ['coffee', null, 'coffees', 'Kaffee', 'food & drink', 'A1', "I'd like a coffee, please.", 'noun'],
  ['tea', null, 'teas', 'Tee', 'food & drink', 'A1', 'A cup of tea, please.', 'noun'],
  ['bill', null, 'bills', 'Rechnung', 'café & restaurant', 'A1', 'Could we have the bill?', 'noun'],
  ['menu', null, 'menus', 'Speisekarte', 'café & restaurant', 'A1', 'Can I see the menu?', 'noun'],
  ['ticket', null, 'tickets', 'Fahrkarte', 'travel', 'A1', 'A return ticket to Leeds, please.', 'noun'],
  ['platform', null, 'platforms', 'Gleis', 'travel', 'A1', 'Which platform does it leave from?', 'noun'],
  ['reservation', null, 'reservations', 'Reservierung', 'travel', 'A1', "I've got a reservation.", 'noun'],
  ['breakfast', null, 'breakfasts', 'Frühstück', 'food & drink', 'A1', 'What time is breakfast?', 'noun'],
  ['straight on', null, null, 'geradeaus', 'directions', 'A1', 'Go straight on.', 'phrase'],
  ['take away', null, null, 'zum Mitnehmen', 'café & restaurant', 'A1', 'To take away, please.', 'phrase'],
  ['headache', null, 'headaches', 'Kopfschmerzen', 'health', 'A1', "I've got a headache.", 'noun'],
  ['change trains', null, null, 'umsteigen', 'travel', 'A2', 'You need to change trains at York.', 'phrase'],
  ['appointment', null, 'appointments', 'Termin', 'everyday', 'A2', "I've got a doctor's appointment.", 'noun'],
  ['delay', null, 'delays', 'Verspätung', 'travel', 'A2', 'There is a 20-minute delay.', 'noun'],
  ['receipt', null, 'receipts', 'Quittung', 'shopping', 'A2', 'Have you got the receipt?', 'noun'],
  ['refund', null, 'refunds', 'Rückerstattung', 'shopping', 'A2', "I'd like a refund.", 'noun'],
  ['colleague', null, 'colleagues', 'Kollege', 'work', 'A2', 'My colleague will help you.', 'noun'],
  ['experience', null, null, 'Erfahrung', 'work', 'B1', 'I have five years of experience.', 'noun'],
  ['complaint', null, 'complaints', 'Beschwerde', 'work', 'B1', "I'd like to make a complaint.", 'noun'],
  ['however', null, null, 'jedoch', 'connectors', 'B1', 'However, there is a problem.', 'adverb'],
  ['in my view', null, null, 'meiner Meinung nach', 'opinion', 'B1', 'In my view, it is too expensive.', 'phrase'],
  ['negotiate', null, null, 'verhandeln', 'business', 'B2', 'We need to negotiate the price.', 'verb'],
  ['compromise', null, 'compromises', 'Kompromiss', 'business', 'B2', "Let's find a compromise.", 'noun'],
  ['objection', null, 'objections', 'Einwand', 'business', 'B2', "That's a fair objection.", 'noun'],
  ['sustainability', null, null, 'Nachhaltigkeit', 'society', 'B2', 'Sustainability matters to our customers.', 'noun'],
];

const ES: Row[] = [
  ['café', 'el', 'cafés', 'coffee', 'food & drink', 'A1', 'Un café con leche, por favor.', 'noun'],
  ['agua', 'el', 'aguas', 'water', 'food & drink', 'A1', 'Un agua sin gas.', 'noun'],
  ['cuenta', 'la', 'cuentas', 'bill', 'café & restaurant', 'A1', 'La cuenta, por favor.', 'noun'],
  ['tostada', 'la', 'tostadas', 'toast', 'food & drink', 'A1', 'Una tostada con tomate.', 'noun'],
  ['billete', 'el', 'billetes', 'ticket', 'travel', 'A1', 'Un billete de ida y vuelta.', 'noun'],
  ['tren', 'el', 'trenes', 'train', 'travel', 'A1', 'El tren sale a las ocho.', 'noun'],
  ['reserva', 'la', 'reservas', 'reservation', 'travel', 'A1', 'Tengo una reserva.', 'noun'],
  ['desayuno', 'el', 'desayunos', 'breakfast', 'food & drink', 'A1', '¿A qué hora es el desayuno?', 'noun'],
  ['todo recto', null, null, 'straight on', 'directions', 'A1', 'Siga todo recto.', 'phrase'],
  ['izquierda', 'la', null, 'left', 'directions', 'A1', 'Gire a la izquierda.', 'noun'],
  ['fiebre', 'la', null, 'fever', 'health', 'A2', 'Tengo fiebre.', 'noun'],
  ['parada', 'la', 'paradas', 'stop', 'travel', 'A2', 'Bájese en la próxima parada.', 'noun'],
  ['equivocarse', null, null, 'to make a mistake', 'everyday', 'A2', 'Me he equivocado de tren.', 'verb'],
  ['experiencia', 'la', 'experiencias', 'experience', 'work', 'B1', 'Tengo experiencia en ventas.', 'noun'],
  ['entrevista', 'la', 'entrevistas', 'interview', 'work', 'B1', 'Mañana tengo una entrevista.', 'noun'],
];

const FR: Row[] = [
  ['café', 'le', 'cafés', 'coffee', 'food & drink', 'A1', 'Un café crème, s\'il vous plaît.', 'noun'],
  ['addition', 'l\'', 'additions', 'bill', 'café & restaurant', 'A1', "L'addition, s'il vous plaît.", 'noun'],
  ['croissant', 'le', 'croissants', 'croissant', 'food & drink', 'A1', 'Je voudrais un croissant.', 'noun'],
  ['billet', 'le', 'billets', 'ticket', 'travel', 'A1', 'Un billet aller-retour.', 'noun'],
  ['gare', 'la', 'gares', 'station', 'travel', 'A1', 'Où est la gare ?', 'noun'],
  ['réservation', 'la', 'réservations', 'reservation', 'travel', 'A1', "J'ai une réservation.", 'noun'],
  ['petit-déjeuner', 'le', 'petits-déjeuners', 'breakfast', 'food & drink', 'A1', 'Le petit-déjeuner est à 7 h.', 'noun'],
  ['tout droit', null, null, 'straight on', 'directions', 'A1', 'Allez tout droit.', 'phrase'],
  ['à gauche', null, null, 'on the left', 'directions', 'A1', 'Tournez à gauche.', 'phrase'],
  ['fièvre', 'la', null, 'fever', 'health', 'A2', "J'ai de la fièvre.", 'noun'],
  ['arrêt', 'l\'', 'arrêts', 'stop', 'travel', 'A2', 'Descendez au prochain arrêt.', 'noun'],
  ['se tromper', null, null, 'to make a mistake', 'everyday', 'A2', 'Je me suis trompé de train.', 'verb'],
  ['expérience', 'l\'', 'expériences', 'experience', 'work', 'B1', "J'ai de l'expérience.", 'noun'],
  ['entretien', 'l\'', 'entretiens', 'interview', 'work', 'B1', "J'ai un entretien demain.", 'noun'],
];

const IT: Row[] = [
  ['caffè', 'il', 'caffè', 'coffee', 'food & drink', 'A1', 'Un caffè, per favore.', 'noun'],
  ['cornetto', 'il', 'cornetti', 'croissant', 'food & drink', 'A1', 'Un cornetto alla crema.', 'noun'],
  ['conto', 'il', 'conti', 'bill', 'café & restaurant', 'A1', 'Il conto, per favore.', 'noun'],
  ['biglietto', 'il', 'biglietti', 'ticket', 'travel', 'A1', 'Un biglietto per Roma.', 'noun'],
  ['stazione', 'la', 'stazioni', 'station', 'travel', 'A1', "Dov'è la stazione?", 'noun'],
  ['prenotazione', 'la', 'prenotazioni', 'reservation', 'travel', 'A1', 'Ho una prenotazione.', 'noun'],
  ['colazione', 'la', 'colazioni', 'breakfast', 'food & drink', 'A1', 'La colazione è alle sette.', 'noun'],
  ['sempre dritto', null, null, 'straight on', 'directions', 'A1', 'Vada sempre dritto.', 'phrase'],
  ['a sinistra', null, null, 'on the left', 'directions', 'A1', 'Giri a sinistra.', 'phrase'],
  ['febbre', 'la', null, 'fever', 'health', 'A2', 'Ho la febbre.', 'noun'],
  ['fermata', 'la', 'fermate', 'stop', 'travel', 'A2', 'Scenda alla prossima fermata.', 'noun'],
  ['sbagliare', null, null, 'to make a mistake', 'everyday', 'A2', 'Ho sbagliato treno.', 'verb'],
  ['esperienza', "l'", 'esperienze', 'experience', 'work', 'B1', 'Ho molta esperienza.', 'noun'],
  ['colloquio', 'il', 'colloqui', 'interview', 'work', 'B1', 'Domani ho un colloquio.', 'noun'],
];

export const VOCABULARY: Record<string, Row[]> = { de: DE, en: EN, es: ES, fr: FR, it: IT };

export function difficultyFor(level: Level): number {
  return { A1: 1, A2: 2, B1: 3, B2: 4 }[level];
}
